{
	"Hello World": {
		"prefix": "alpha",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nint main() {",
			"\tcout << \"Hello World$1\" << endl;$2",
			"\treturn 0;",
			"}"
		],
		"description": "Log output to console"
	},
	"cpp_priority_queue": {
		"prefix": "priority_queue",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"",
			"// Node structure for priority queue",
			"struct Node {",
			"    int value;      // The value of the element",
			"    int priority;   // The priority of the element",
			"    Node* next;     // Pointer to the next node in the queue",
			"",
			"    Node(int val, int pri) : value(val), priority(pri), next(nullptr) {}",
			"};",
			"",
			"// PriorityQueue class",
			"class PriorityQueue {",
			"private:",
			"    Node* front; // The front of the queue",
			"",
			"public:",
			"    // Constructor",
			"    PriorityQueue() : front(nullptr) {}",
			"",
			"    // Destructor to free the memory",
			"    ~PriorityQueue() {",
			"        while (front) {",
			"            Node* temp = front;",
			"            front = front->next;",
			"            delete temp;",
			"        }",
			"    }",
			"",
			"    // Insert a new element with a given priority",
			"    void insert(int val, int pri) {",
			"        Node* newNode = new Node(val, pri);",
			"",
			"        // If the queue is empty or the new node has higher priority than the front",
			"        if (!front || pri > front->priority) {",
			"            newNode->next = front;",
			"            front = newNode;",
			"        } else {",
			"            // Otherwise, find the correct position based on priority",
			"            Node* current = front;",
			"            while (current->next && current->next->priority >= pri) {",
			"                current = current->next;",
			"            }",
			"            newNode->next = current->next;",
			"            current->next = newNode;",
			"        }",
			"    }",
			"",
			"    // Remove the element with the highest priority (front of the queue)",
			"    void remove() {",
			"        if (!front) {",
			"            cout << \"Queue is empty!\" << endl;",
			"            return;",
			"        }",
			"        Node* temp = front;",
			"        front = front->next;",
			"        delete temp;",
			"    }",
			"",
			"    // Get the element with the highest priority (front of the queue)",
			"    int peek() {",
			"        if (!front) {",
			"            cout << \"Queue is empty!\" << endl;",
			"            return -1; // Error value",
			"        }",
			"        return front->value;",
			"    }",
			"",
			"    // Print the entire queue (from front to back)",
			"    void printQueue() {",
			"        if (!front) {",
			"            cout << \"Queue is empty!\" << endl;",
			"            return;",
			"        }",
			"        Node* current = front;",
			"        while (current) {",
			"            cout << \"(\" << current->value << \", \" << current->priority << \") \";",
			"            current = current->next;",
			"        }",
			"        cout << endl;",
			"    }",
			"};",
			"",
			"int main() {",
			"    PriorityQueue pq;",
			"",
			"    pq.insert(10, 3);  // Element 10 with priority 3",
			"    pq.insert(20, 5);  // Element 20 with priority 5",
			"    pq.insert(30, 2);  // Element 30 with priority 2",
			"    pq.insert(40, 4);  // Element 40 with priority 4",
			"",
			"    cout << \"Priority Queue: \";",
			"    pq.printQueue();",
			"",
			"    cout << \"Element with highest priority: \" << pq.peek() << endl;",
			"",
			"    pq.remove();  // Remove the element with highest priority",
			"    cout << \"After removing the highest priority element: \";",
			"    pq.printQueue();",
			"",
			"    pq.remove();  // Remove another element",
			"    cout << \"After removing another element: \";",
			"    pq.printQueue();",
			"",
			"    return 0;",
			"}"
		],
		"description": "C++ Program for Priority Queue using Linked List"
	},
	"cpp_hashtable": {
		"prefix": "separate_chaining",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"",
			"class Node",
			"{",
			"public:",
			"    string data;",
			"    Node *next;",
			"",
			"    Node(string val)",
			"    {",
			"        data = val;",
			"        next = NULL;",
			"    }",
			"};",
			"",
			"class HashTable",
			"{",
			"private:",
			"    Node **table;",
			"    int size;",
			"",
			"public:",
			"    HashTable(int s)",
			"    {",
			"        size = s;",
			"        table = new Node *[size];",
			"        for (int i = 0; i < size; i++)",
			"        {",
			"            table[i] = NULL;",
			"        }",
			"    }",
			"",
			"    int hashfunc(string key)",
			"    {",
			"        int sum = 0;",
			"        for (int i = 0; i < key.length(); i++)",
			"        {",
			"            sum += int(key[i]);",
			"        }",
			"",
			"        return sum % size;",
			"    }",
			"",
			"    void insert(string key)",
			"    {",
			"        int index = hashfunc(key);",
			"        Node *newNode = new Node(key);",
			"        if (table[index] == NULL)",
			"        {",
			"            table[index] = newNode;",
			"        }",
			"        else",
			"        {",
			"            Node *temp = table[index];",
			"            while (temp->next != NULL)",
			"            {",
			"                temp = temp->next;",
			"            }",
			"            temp->next = newNode;",
			"        }",
			"    }",
			"",
			"    void display()",
			"    {",
			"        for (int i = 0; i < size; i++)",
			"        {",
			"            cout << \"Index \" << i << \": \";",
			"            Node *temp = table[i];",
			"            while (temp)",
			"            {",
			"                cout << temp->data << \" \";",
			"                temp = temp->next;",
			"            }",
			"            cout << endl;",
			"        }",
			"    }",
			"};",
			"",
			"int main()",
			"{",
			"    HashTable h(5);",
			"    h.insert(\"apple\");",
			"    h.insert(\"mango\");",
			"    h.insert(\"banana\");",
			"    h.insert(\"orange\");",
			"    h.display();",
			"}"
		],
		"description": "C++ Hash Table with separate chaining (Linked List) implementation"
	},
	"Quick Sort": {
		"prefix": "quick",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nint partition(int arr[], int low, int high) {",
			"\tint pivot = arr[high];",
			"\tint i = low - 1;",
			"\n\tfor (int j = low; j < high; j++) {",
			"\t\tif (arr[j] <= pivot) {",
			"\t\t\ti++;",
			"\t\t\tswap(arr[i], arr[j]);",
			"\t\t}",
			"\t}",
			"\tswap(arr[i + 1], arr[high]);",
			"\treturn i + 1;",
			"}",
			"\nvoid quickSort(int arr[], int low, int high) {",
			"\tif (low < high) {",
			"\t\tint pi = partition(arr, low, high);",
			"\t\tquickSort(arr, low, pi - 1);",
			"\t\tquickSort(arr, pi + 1, high);",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t}",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {10, 7, 8, 9, 1, 5};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tquickSort(arr, 0, n - 1);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Quick Sort implementation"
	},
	"MergeSort": {
		"prefix": "merge",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nvoid merge(int arr[], int left, int mid, int right) {",
			"\tint n1 = mid - left + 1;",
			"\tint n2 = right - mid;",
			"\tint* L = new int[n1];",
			"\tint* R = new int[n2];",
			"\n\tfor (int i = 0; i < n1; i++)",
			"\t\tL[i] = arr[left + i];",
			"\n\tfor (int j = 0; j < n2; j++)",
			"\t\tR[j] = arr[mid + 1 + j];",
			"\n\tint i = 0, j = 0, k = left;",
			"\n\twhile (i < n1 && j < n2) {",
			"\t\tif (L[i] <= R[j]) {",
			"\t\t\tarr[k] = L[i];",
			"\t\t\ti++;",
			"\t\t} else {",
			"\t\t\tarr[k] = R[j];",
			"\t\t\tj++;",
			"\t\t}",
			"\t\tk++;",
			"\t}",
			"\n\twhile (i < n1) {",
			"\t\tarr[k] = L[i];",
			"\t\ti++;",
			"\t\tk++;",
			"\t}",
			"\n\twhile (j < n2) {",
			"\t\tarr[k] = R[j];",
			"\t\tj++;",
			"\t\tk++;",
			"\t}",
			"\n\tdelete[] L;",
			"\tdelete[] R;",
			"}",
			"\nvoid mergeSort(int arr[], int left, int right) {",
			"\tif (left < right) {",
			"\t\tint mid = left + (right - left) / 2;",
			"\n\t\tmergeSort(arr, left, mid);",
			"\t\tmergeSort(arr, mid + 1, right);",
			"\t\tmerge(arr, left, mid, right);",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t}",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {12, 11, 13, 5, 6, 7};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tmergeSort(arr, 0, n - 1);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Merge Sort implementation"
	},
	"BubbleSort": {
		"prefix": "bubble",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nvoid bubbleSort(int arr[], int n) {",
			"\tfor (int i = 0; i < n - 1; i++) {",
			"\t\tfor (int j = 0; j < n - i - 1; j++) {",
			"\t\t\tif (arr[j] > arr[j + 1]) {",
			"\t\t\t\tswap(arr[j], arr[j + 1]);",
			"\t\t\t}",
			"\t\t}",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t}",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {64, 34, 25, 12, 22, 11, 90};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tbubbleSort(arr, n);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Bubble Sort implementation"
	},
	"SelectionSort": {
		"prefix": "selection",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nvoid selectionSort(int arr[], int n) {",
			"\tfor (int i = 0; i < n - 1; i++) {",
			"\t\tint minIndex = i;",
			"\t\tfor (int j = i + 1; j < n; j++) {",
			"\t\t\tif (arr[j] < arr[minIndex]) {",
			"\t\t\t\tminIndex = j;",
			"\t\t\t}",
			"\t\t}",
			"\t\tswap(arr[minIndex], arr[i]);",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t}",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {29, 10, 14, 37, 13};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tselectionSort(arr, n);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Selection Sort implementation"
	},
	"InsertionSort": {
		"prefix": "insertion",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nvoid insertionSort(int arr[], int n) {",
			"\tfor (int i = 1; i < n; i++) {",
			"\t\tint key = arr[i];",
			"\t\tint j = i - 1;",
			"\n\t\twhile (j >= 0 && arr[j] > key) {",
			"\t\t\tarr[j + 1] = arr[j];",
			"\t\t\tj--;",
			"\t\t}",
			"\t\tarr[j + 1] = key;",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t}",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {12, 11, 13, 5, 6};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tinsertionSort(arr, n);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Insertion Sort implementation"
	},
	"RadixSort": {
		"prefix": "radix",
		"body": [
			"#include <iostream>",
			"#include <vector>",
			"using namespace std;",
			"\nint getMax(int arr[], int n) {",
			"\tint max = arr[0];",
			"\tfor (int i = 1; i < n; i++) {",
			"\t\tif (arr[i] > max) max = arr[i];",
			"\t}",
			"\treturn max;",
			"}",
			"\nvoid countingSort(int arr[], int n, int exp) {",
			"\tvector<int> output(n);",
			"\tint count[10] = {0};",
			"\n\tfor (int i = 0; i < n; i++) {",
			"\t\tcount[(arr[i] / exp) % 10]++;",
			"\t}",
			"\n\tfor (int i = 1; i < 10; i++) {",
			"\t\tcount[i] += count[i - 1];",
			"\t}",
			"\n\tfor (int i = n - 1; i >= 0; i--) {",
			"\t\toutput[count[(arr[i] / exp) % 10] - 1] = arr[i];",
			"\t\tcount[(arr[i] / exp) % 10]--;",
			"\t}",
			"\n\tfor (int i = 0; i < n; i++) {",
			"\t\tarr[i] = output[i];",
			"\t}",
			"}",
			"\nvoid radixSort(int arr[], int n) {",
			"\tint max = getMax(arr, n);",
			"\n\tfor (int exp = 1; max / exp > 0; exp *= 10) {",
			"\t\tcountingSort(arr, n, exp);",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t} ",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {170, 45, 75, 90, 802, 24, 2, 66};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tradixSort(arr, n);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Radix Sort implementation"
	},
	"ShellSort": {
		"prefix": "shell",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nvoid shellSort(int arr[], int n) {",
			"\tfor (int gap = n / 2; gap > 0; gap /= 2) {",
			"\t\tfor (int i = gap; i < n; i++) {",
			"\t\t\tint temp = arr[i];",
			"\t\t\tint j;",
			"\n\t\t\tfor (j = i; j >= gap && arr[j - gap] > temp; j -= gap) {",
			"\t\t\t\tarr[j] = arr[j - gap];",
			"\t\t\t}",
			"\t\t\tarr[j] = temp;",
			"\t\t}",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t} ",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {12, 34, 54, 2, 3};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tshellSort(arr, n);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Shell Sort implementation"
	},
	"CombSort": {
		"prefix": "comb",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nvoid combSort(int arr[], int n) {",
			"\tfloat shrink = 1.3;  // shrink factor",
			"\tint gap = n;",
			"\tbool swapped = true;",
			"\n\twhile (gap > 1 || swapped) {",
			"\t\tif (gap > 1) {",
			"\t\t\tgap = static_cast<int>(gap / shrink);",
			"\t\t}",
			"\n\t\tswapped = false;",
			"\t\tfor (int i = 0; i + gap < n; i++) {",
			"\t\t\tif (arr[i] > arr[i + gap]) {",
			"\t\t\t\tswap(arr[i], arr[i + gap]);",
			"\t\t\t\tswapped = true;",
			"\t\t\t}",
			"\t\t}",
			"\t}",
			"}",
			"\nvoid printArray(const int arr[], int size) {",
			"\tfor (int i = 0; i < size; i++) {",
			"\t\tcout << arr[i] << \" \";",
			"\t} ",
			"\tcout << endl;",
			"}",
			"\nint main() {",
			"\tint arr[] = {64, 34, 25, 12, 22, 11, 90};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\n\tcout << \"Original array: \";",
			"\tprintArray(arr, n);",
			"\n\tcombSort(arr, n);",
			"\n\tcout << \"Sorted array: \";",
			"\tprintArray(arr, n);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Comb Sort implementation"
	},
	"BinarySearch": {
		"prefix": "binary",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nint binarySearch(int arr[], int n, int x) {",
			"\tint left = 0, right = n - 1;",
			"\n\twhile (left <= right) {",
			"\t\tint mid = left + (right - left) / 2;",
			"\n\t\tif (arr[mid] == x) {",
			"\t\t\treturn mid;",
			"\t\t} else if (arr[mid] < x) {",
			"\t\t\tleft = mid + 1;",
			"\t\t} else {",
			"\t\t\tright = mid - 1;",
			"\t\t}",
			"\t}",
			"\n\treturn -1;  // Element not found",
			"}",
			"\nvoid printResult(int result) {",
			"\tif (result != -1) {",
			"\t\tcout << \"Element found at index: \" << result << endl;",
			"\t} else {",
			"\t\tcout << \"Element not found\" << endl;",
			"\t}",
			"}",
			"\nint main() {",
			"\tint arr[] = {2, 3, 4, 10, 40};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\tint x = 10;  // Element to search for",
			"\n\tint result = binarySearch(arr, n, x);",
			"\n\tprintResult(result);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Binary Search implementation"
	},
	"InterpolationSearch": {
		"prefix": "interpolation",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nint interpolationSearch(int arr[], int n, int x) {",
			"\tint low = 0, high = n - 1;",
			"\n\twhile (low <= high && x >= arr[low] && x <= arr[high]) {",
			"\t\tif (low == high) {",
			"\t\t\tif (arr[low] == x) return low;",
			"\t\t\treturn -1;",
			"\t\t}",
			"\n\t\tint pos = low + ((double)(high - low) / (arr[high] - arr[low]) * (x - arr[low]));",
			"\n\t\tif (arr[pos] == x) {",
			"\t\t\treturn pos;",
			"\t\t} else if (arr[pos] < x) {",
			"\t\t\tlow = pos + 1;",
			"\t\t} else {",
			"\t\t\thigh = pos - 1;",
			"\t\t}",
			"\t}",
			"\n\treturn -1;  // Element not found",
			"}",
			"\nvoid printResult(int result) {",
			"\tif (result != -1) {",
			"\t\tcout << \"Element found at index: \" << result << endl;",
			"\t} else {",
			"\t\tcout << \"Element not found\" << endl;",
			"\t}",
			"}",
			"\nint main() {",
			"\tint arr[] = {10, 20, 30, 40, 50};",
			"\tint n = sizeof(arr) / sizeof(arr[0]);",
			"\tint x = 30;  // Element to search for",
			"\n\tint result = interpolationSearch(arr, n, x);",
			"\n\tprintResult(result);",
			"\n\treturn 0;",
			"}"
		],
		"description": "Interpolation Search implementation"
	},
	"N Queens Problem": {
	"prefix": "n_queens",
	"body": [
		"#include <iostream>",
		"using namespace std;",
		"const int N = 4;",
		"",
		"bool isSafe(int board[N][N], int row, int col) {",
		"\tfor (int i = 0; i < row; i++)",
		"\t\tif (board[i][col] == 1)",
		"\t\t\treturn false;",
		"",
		"\tfor (int i = row - 1, j = col - 1; i >= 0 && j >= 0; i--, j--)",
		"\t\tif (board[i][j] == 1)",
		"\t\t\treturn false;",
		"",
		"\tfor (int i = row - 1, j = col + 1; i >= 0 && j < N; i--, j++)",
		"\t\tif (board[i][j] == 1)",
		"\t\t\treturn false;",
		"",
		"\treturn true;",
		"}",
		"",
		"bool solveNQ(int board[N][N], int row) {",
		"\tif (row == N) {",
		"\t\tfor (int i = 0; i < N; i++, cout << endl)",
		"\t\t\tfor (int j = 0; j < N; j++)",
		"\t\t\t\tcout << (board[i][j] ? \"Q \" : \". \");",
		"\t\tcout << endl;",
		"\t\treturn true;",
		"\t}",
		"",
		"\tbool res = false;",
		"\tfor (int col = 0; col < N; col++) {",
		"\t\tif (isSafe(board, row, col)) {",
		"\t\t\tboard[row][col] = 1;",
		"\t\t\tres = solveNQ(board, row + 1) || res;",
		"\t\t\tboard[row][col] = 0;",
		"\t\t}",
		"\t}",
		"\treturn res;",
		"}",
		"",
		"int main() {",
		"\tint board[N][N] = {0};",
		"\tif (!solveNQ(board, 0))",
		"\t\tcout << \"No solution exists.\";",
		"\treturn 0;",
		"}"
	],
	"description": "Solve N-Queens problem using recursion and backtracking"
},
	"Lion in a Maze": {
		"prefix": "lion_in_a_maze",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"const int N = 5;",
			"\nbool solveMaze(int maze[N][N], int x, int y, int solution_array[N][N]) {",
			"\tif ((x == N - 1) && (y == N - 1) && (maze[x][y] == 1)) {",
			"\t\tsolution_array[x][y] = 1;",
			"\t\treturn true;",
			"\t}",
			"\tif ((x >= 0) && (y >= 0) && (x < N) && (y < N) && (maze[x][y] == 1)) {",
			"\t\tsolution_array[x][y] = 1;",
			"\t\tif (solveMaze(maze, x + 1, y, solution_array) || solveMaze(maze, x, y + 1, solution_array)) {",
			"\t\t\treturn true;",
			"\t\t}",
			"\t\tsolution_array[x][y] = 0;",
			"\t\treturn false;",
			"\t}",
			"\treturn false;",
			"}",
			"\nint main() {",
			"\tint maze[N][N] = {{1, 0, 1, 0, 1},",
			"\t\t\t\t{1, 1, 1, 1, 1},",
			"\t\t\t\t{0, 1, 0, 1, 1},",
			"\t\t\t\t{1, 0, 0, 1, 1},",
			"\t\t\t\t{1, 1, 1, 0, 1}};",
			"\tint solution_array[N][N] = {0};",
			"\tif (solveMaze(maze, 0, 0, solution_array)) {",
			"\t\tcout << \"The lion has reached the meat...!\" << endl << endl;",
			"\t\tcout << \"Solution array:\" << endl;",
			"\t\tfor (int i = 0; i < N; ++i) {",
			"\t\t\tfor (int j = 0; j < N; ++j) {",
			"\t\t\t\tcout << solution_array[i][j] << \" \";",
			"\t\t\t}",
			"\t\t\tcout << endl;",
			"\t\t}",
			"\t\tcout << \"-----------------------\" << endl;",
			"\t} else {",
			"\t\tcout << \"The lion could not reach the meat.\" << endl;",
			"\t}",
			"\treturn 0;",
			"}"
		],
		"description": "Solve Lion in a Maze problem using recursive backtracking"
	},
	"NQueens": {
		"prefix": "n_flags",
		"body": [
			"#include <iostream>",
			"#include <cmath>",
			"using namespace std;",
			"\nconst int N = 4;",
			"int maximum_flags = 0;",
			"\nbool isSafe(int grid[], int row, int col) {",
			"\tfor (int i = 0; i < row; i++) {",
			"\t\tif ((grid[i] == col) || ((abs(grid[i] - col)) == (abs(i - row)))) {",
			"\t\t\treturn false;",
			"\t\t}",
			"\t}",
			"\treturn true;",
			"}",
			"\nvoid placeFlags(int grid[], int row, int flagsPlaced) {",
			"\tif (row == N) {",
			"\t\tmaximum_flags = max(maximum_flags, flagsPlaced);",
			"\t\treturn;",
			"\t}",
			"\n\tfor (int col = 0; col < N; col++) {",
			"\t\tif (isSafe(grid, row, col)) {",
			"\t\t\tgrid[row] = col;",
			"\t\t\tplaceFlags(grid, row + 1, flagsPlaced + 1);",
			"\t\t\tgrid[row] = -1;",
			"\t\t}",
			"\t}",
			"\tplaceFlags(grid, row + 1, flagsPlaced);",
			"}",
			"\nint main() {",
			"\tint grid[N];",
			"\tfor (int i = 0; i < N; i++) {",
			"\t\tgrid[i] = -1;",
			"\t}",
			"\tplaceFlags(grid, 0, 0);",
			"\tcout << \"Maximum number of flags that can be placed: \" << maximum_flags << endl;",
			"\treturn 0;",
			"}"
		],
		"description": "Solve N-Queens problem using recursive backtracking"
	},
	"Singly Linked List": {
		"prefix": "singly_linked_list",
		"body": [
			"#include <iostream>\n",
			"using namespace std;\n",
			"\n",
			"class Node {",
			"public:",
			"\tint data;",
			"\tNode *next;\n",
			"\tNode(int val) {",
			"\t\tdata = val;",
			"\t\tnext = NULL;",
			"\t}",
			"};\n",
			"class singlyLL {",
			"public:",
			"\tNode *head;",
			"\tNode *tail;\n",
			"\tsinglyLL() {",
			"\t\thead = NULL;",
			"\t\ttail = NULL;",
			"\t}\n",
			"\t// Insert at the end of the linked list",
			"\tvoid insertAtEnd(int val) {",
			"\t\tNode *n = new Node(val);\n",
			"\t\tif (head == NULL) {",
			"\t\t\thead = n;",
			"\t\t\ttail = n;",
			"\t\t\treturn;",
			"\t\t}",
			"\t\ttail->next = n;",
			"\t\ttail = n;",
			"\t\tcout << \"Successfully inserted!\" << endl;",
			"\t}\n",
			"\t// Insert at the start of the linked list",
			"\tvoid insertAtStart(int val) {",
			"\t\tNode *n = new Node(val);",
			"\t\tn->next = head;",
			"\t\thead = n;",
			"\t\tif(tail == NULL)",
			"\t\t\ttail = n;",
			"\t}\n",
			"\t// Insert after a specific position",
			"\tvoid insertAfter(int pos, int val) {",
			"\t\tNode *n = new Node(val);",
			"\t\tNode *curr;",
			"\t\tNode *prev;",
			"\t\tcurr = head;",
			"\t\tfor (int i = 0; i < pos; i++) {",
			"\t\t\tprev = curr;",
			"\t\t\tcurr = curr->next;",
			"\t\t}",
			"\t\tprev->next = n;",
			"\t\tn->next = curr;",
			"\t}\n",
			"\t// Delete from the end of the linked list",
			"\tvoid deleteFromEnd() {",
			"\t\tNode *temp = head;",
			"\t\tNode *prev;\n",
			"\t\tif(head == NULL)",
			"\t\t\treturn;\n",
			"\t\tif(head->next == NULL) {",
			"\t\t\tdelete head;",
			"\t\t\thead = NULL;",
			"\t\t\ttail = NULL;",
			"\t\t\treturn;",
			"\t\t}\n",
			"\t\twhile (temp->next != NULL) {",
			"\t\t\tprev = temp;",
			"\t\t\ttemp = temp->next;",
			"\t\t}",
			"\t\tprev->next = NULL;",
			"\t\ttail = prev;",
			"\t\tdelete temp;",
			"\t}\n",
			"\t// Delete from the start of the linked list",
			"\tvoid deleteFromStart() {",
			"\t\tif(head == NULL)",
			"\t\t\treturn;\n",
			"\t\tNode *temp = head;",
			"\t\thead = temp->next;\n",
			"\t\tif(head == NULL)",
			"\t\t\ttail = NULL;\n",
			"\t\tdelete temp;",
			"\t}\n",
			"\t// Delete after a specific index",
			"\tvoid deleteAfter(int index) {",
			"\t\tNode *curr = head;",
			"\t\tNode *prev;\n",
			"\t\tif(head == NULL || index < 0)",
			"\t\t\treturn;\n",
			"\t\tif(index == 0) {",
			"\t\t\tdeleteFromStart();",
			"\t\t\treturn;",
			"\t\t}\n",
			"\t\tfor (int i = 0; i < index; i++) {",
			"\t\t\tprev = curr;",
			"\t\t\tcurr = curr->next;",
			"\t\t\tif(curr == NULL)",
			"\t\t\t\treturn;",
			"\t\t}\n",
			"\t\tif(curr->next == NULL)",
			"\t\t\ttail = prev;\n",
			"\t\tprev->next = curr->next;",
			"\t\tdelete curr;",
			"\t}\n",
			"\t// Display the linked list",
			"\tvoid Display() {",
			"\t\tNode *temp = head;",
			"\t\twhile (temp != NULL) {",
			"\t\t\tcout << temp->data << \" \";",
			"\t\t\ttemp = temp->next;",
			"\t\t}",
			"\t\tcout << endl;",
			"\t}",
			"};\n",
			"int main() {",
			"\tsinglyLL list;",
			"\tlist.insertAtStart(12);",
			"\tlist.insertAtStart(34);",
			"\tlist.insertAtStart(23);",
			"\tlist.Display(); // 23 34 12",
			"\tcout << endl;\n",
			"\tlist.insertAtStart(67);",
			"\tlist.insertAtStart(15);",
			"\tlist.insertAfter(2, 76);",
			"\tlist.Display(); // 15 67 76 23 34 12\n",
			"\tlist.deleteAfter(4); // 15 67 76 23 12",
			"\tlist.Display();\n",
			"\tlist.deleteFromStart();",
			"\tlist.deleteFromEnd();",
			"\tlist.Display(); // 67 76 23\n",
			"\treturn 0;",
			"}"
		],
		"description": "C++ Singly Linked List implementation with helper functions."
	},
	"Doubly Linked List": {
		"prefix": "doubly_linked_list",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"\nclass Node {",
			"public:",
			"\tint data;",
			"\tNode* next;",
			"\tNode* prev;",
			"\n\tNode(int val) {",
			"\t\tdata = val;",
			"\t\tnext = NULL;",
			"\t\tprev = NULL;",
			"\t}",
			"};",
			"\nclass doublyLL {",
			"public:",
			"\tNode* head;",
			"\tNode* tail;",
			"\n\tdoublyLL() {",
			"\t\thead = NULL;",
			"\t\ttail = NULL;",
			"\t}",
			"\n\t// Insert at the end of the linked list",
			"\tvoid insertAtEnd(int val) {",
			"\t\tNode* n = new Node(val);",
			"\t\tif (head == NULL) {",
			"\t\t\thead = n;",
			"\t\t\ttail = n;",
			"\t\t\treturn;",
			"\t\t}",
			"\t\ttail->next = n;",
			"\t\tn->prev = tail;",
			"\t\ttail = n;",
			"\t\tcout << \"Successfully inserted at end!\" << endl;",
			"\t}",
			"\n\t// Insert at the start of the linked list",
			"\tvoid insertAtStart(int val) {",
			"\t\tNode* n = new Node(val);",
			"\t\tif (head == NULL) {",
			"\t\t\thead = n;",
			"\t\t\ttail = n;",
			"\t\t\treturn;",
			"\t\t}",
			"\t\tn->next = head;",
			"\t\thead->prev = n;",
			"\t\thead = n;",
			"\t\tcout << \"Successfully inserted at start!\" << endl;",
			"\t}",
			"\n\t// Insert after a specific position",
			"\tvoid insertAfter(int pos, int val) {",
			"\t\tNode* n = new Node(val);",
			"\t\tNode* curr = head;",
			"\t\tfor (int i = 0; i < pos; i++) {",
			"\t\t\tcurr = curr->next;",
			"\t\t\tif (curr == NULL) return;",
			"\t\t}",
			"\t\tn->next = curr->next;",
			"\t\tn->prev = curr;",
			"\t\tif (curr->next != NULL) {",
			"\t\t\tcurr->next->prev = n;",
			"\t\t} else {",
			"\t\t\ttail = n;",
			"\t\t}",
			"\t\tcurr->next = n;",
			"\t}",
			"\n\t// Delete from the end of the linked list",
			"\tvoid deleteFromEnd() {",
			"\t\tif (tail == NULL) return;",
			"\t\tif (head == tail) {",
			"\t\t\tdelete head;",
			"\t\t\thead = NULL;",
			"\t\t\ttail = NULL;",
			"\t\t\treturn;",
			"\t\t}",
			"\t\tNode* temp = tail;",
			"\t\ttail = tail->prev;",
			"\t\ttail->next = NULL;",
			"\t\tdelete temp;",
			"\t}",
			"\n\t// Delete from the start of the linked list",
			"\tvoid deleteFromStart() {",
			"\t\tif (head == NULL) return;",
			"\t\tif (head == tail) {",
			"\t\t\tdelete head;",
			"\t\t\thead = NULL;",
			"\t\t\ttail = NULL;",
			"\t\t\treturn;",
			"\t\t}",
			"\t\tNode* temp = head;",
			"\t\thead = head->next;",
			"\t\thead->prev = NULL;",
			"\t\tdelete temp;",
			"\t}",
			"\n\t// Delete after a specific index",
			"\tvoid deleteAfter(int index) {",
			"\t\tNode* curr = head;",
			"\t\tif (head == NULL || index < 0) return;",
			"\t\tfor (int i = 0; i < index; i++) {",
			"\t\t\tcurr = curr->next;",
			"\t\t\tif (curr == NULL || curr->next == NULL) return;",
			"\t\t}",
			"\t\tNode* toDelete = curr->next;",
			"\t\tcurr->next = toDelete->next;",
			"\t\tif (toDelete->next != NULL) {",
			"\t\t\ttoDelete->next->prev = curr;",
			"\t\t} else {",
			"\t\t\ttail = curr;",
			"\t\t}",
			"\t\tdelete toDelete;",
			"\t}",
			"\n\t// Display the linked list",
			"\tvoid Display() {",
			"\t\tNode* temp = head;",
			"\t\twhile (temp != NULL) {",
			"\t\t\tcout << temp->data << \" \";",
			"\t\t\ttemp = temp->next;",
			"\t\t}",
			"\t\tcout << endl;",
			"\t}",
			"};",
			"\nint main() {",
			"\tdoublyLL list;",
			"\tlist.insertAtStart(12);",
			"\tlist.insertAtStart(34);",
			"\tlist.insertAtStart(23);",
			"\tlist.Display(); // 23 34 12",
			"\tcout << endl;",
			"\n\tlist.insertAtStart(67);",
			"\tlist.insertAtStart(15);",
			"\tlist.insertAfter(2, 76);",
			"\tlist.Display(); // 15 67 76 23 34 12",
			"\n\tlist.deleteAfter(4); // 15 67 76 23 12",
			"\tlist.Display();",
			"\n\tlist.deleteFromStart();",
			"\tlist.deleteFromEnd();",
			"\tlist.Display(); // 67 76 23",
			"\treturn 0;",
			"}"
		],
		"description": "Doubly Linked List with helper functions"
	},
	"Stack using arrays": {
		"prefix": "Stack_using_arrays",
		"body": [
			"#include <iostream>",
			"#include <cstring>",
			"using namespace std;",
			"const int MAX = 100;",
			"",
			"class Stack{",
			"    char data[MAX];",
			"    int top;",
			"",
			"public:",
			"    Stack() : top(-1) {}",
			"",
			"    void push(char value);",
			"    char pop();",
			"    char peek();",
			"    bool is_empty();",
			"    bool is_full();",
			"};",
			"",
			"void Stack::push(char value){",
			"    if (top < (MAX - 1)){",
			"        data[++top] = value;",
			"    }",
			"    else{",
			"        cout << \"Stack Overflow!\" << endl;",
			"    }",
			"}",
			"",
			"char Stack::pop(){",
			"    if (top >= 0)",
			"    {",
			"        return data[top--];",
			"    }",
			"    else{",
			"        cout << \"Stack Underflow!\" << endl;",
			"        return ' ';",
			"    }",
			"}",
			"",
			"char Stack::peek(){",
			"    if (top < 0)",
			"    {",
			"        cout << \"Empty Stack!\" << endl;",
			"        return 0;",
			"    }",
			"    return data[top];",
			"}",
			"",
			"bool Stack::is_empty(){",
			"    return (top < 0);",
			"}",
			"",
			"bool Stack::is_full(){",
			"    return (top >= MAX - 1);",
			"}",
			"",
			"int main(){",
			"    Stack stack;",
			"",
			"    // pushing elements to the stack",
			"    stack.push('A');",
			"    stack.push('B');",
			"    stack.push('C');",
			"    cout << \"After pushing A, B, C: \" << endl;",
			"    cout << \"Top element is: \" << stack.peek() << endl;",
			"",
			"    // popping elements from the stack",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"    cout << \"After popping, top element is: \" << stack.peek() << endl;",
			"",
			"    // Check if stack is empty",
			"    if (stack.is_empty())",
			"        cout << \"Stack is empty!\" << endl;",
			"    else",
			"        cout << \"Stack is not empty!\" << endl;",
			"",
			"    // popping all elements",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"",
			"    // popping from an empty stack (underflow)",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"",
			"    // Check if stack is empty after all pops",
			"    if (stack.is_empty())",
			"        cout << \"Stack is empty after popping all elements!\" << endl;",
			"",
			"    // pushing elements till the stack overflows",
			"    cout << \"Pushing elements until overflow:\" << endl;",
			"",
			"    for (int i = 0; i < MAX + 1; i++){",
			"        stack.push('X');",
			"    }",
			"    return 0;",
			"}"
		],
		"description": "C++ implementation of a stack data structure"
	},
	"Stack using linked list": {
		"prefix": "stack_using_linked_list",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"",
			"class Node",
			"{",
			"public:",
			"    char data;",
			"    Node *next;",
			"};",
			"",
			"const int MAX = 100;",
			"class Stack",
			"{",
			"    Node *top;",
			"    int size;",
			"",
			"public:",
			"    Stack() : top(nullptr), size(0) {}",
			"",
			"    void push(char value);",
			"    char pop();",
			"    char peek();",
			"    bool is_empty();",
			"    bool is_full();",
			"};",
			"",
			"void Stack::push(char value)",
			"{",
			"    if (size < MAX || MAX == 0)",
			"    {",
			"        Node *newNode = new Node();",
			"        newNode->data = value;",
			"        newNode->next = top;",
			"        top = newNode;",
			"        size++;",
			"    }",
			"    else",
			"    {",
			"        cout << \"Stack Overflow!\" << endl;",
			"    }",
			"}",
			"",
			"char Stack::pop()",
			"{",
			"    if (top != nullptr)",
			"    {",
			"        char value = top->data;",
			"        Node *temp = top;",
			"        top = top->next;",
			"        delete temp;",
			"        size--;",
			"        return value;",
			"    }",
			"    else",
			"    {",
			"        cout << \"Stack Underflow!\" << endl;",
			"        return ' ';",
			"    }",
			"}",
			"",
			"char Stack::peek()",
			"{",
			"    if (top != nullptr)",
			"    {",
			"        return top->data;",
			"    }",
			"    else",
			"    {",
			"        cout << \"Empty Stack!\" << endl;",
			"        return 0;",
			"    }",
			"}",
			"",
			"bool Stack::is_empty()",
			"{",
			"    return (top == nullptr);",
			"}",
			"",
			"bool Stack::is_full()",
			"{",
			"    return (size >= MAX && MAX != 0);",
			"}",
			"",
			"int main()",
			"{",
			"    Stack stack;",
			"",
			"    stack.push('A');",
			"    stack.push('B');",
			"    stack.push('C');",
			"    cout << \"After pushing A, B, C: \" << endl;",
			"    cout << \"Top element is: \" << stack.peek() << endl;",
			"",
			"    // Popping elements from the stack",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"    cout << \"After popping, top element is: \" << stack.peek() << endl;",
			"",
			"    // Check if stack is empty",
			"    if (stack.is_empty())",
			"        cout << \"Stack is empty!\" << endl;",
			"    else",
			"        cout << \"Stack is not empty!\" << endl;",
			"",
			"    // Popping all elements",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"",
			"    // Popping from an empty stack (underflow)",
			"    cout << \"Popped element: \" << stack.pop() << endl;",
			"",
			"    // Check if stack is empty after all pops",
			"    if (stack.is_empty())",
			"        cout << \"Stack is empty after popping all elements!\" << endl;",
			"",
			"    // Pushing elements until overflow (optional)",
			"    cout << \"Pushing elements until overflow:\" << endl;",
			"",
			"    for (int i = 0; i < MAX + 1; i++)",
			"    {",
			"        stack.push('X');",
			"    }",
			"    return 0;",
			"}"
		],
		"description": "A basic implementation of a stack data structure in C++"
	},
	"bt_to_bst": {
		"prefix": "bt_to_bst",
		"body": [
			"#include <iostream>",
			"#include <algorithm>",
			"using namespace std;",
			"class TreeNode {",
			"public:",
			"    int data;",
			"    TreeNode *left;",
			"    TreeNode *right;",
			"    TreeNode(int d = 0) : data(d), left(nullptr), right(nullptr) {}",
			"};",
			"int count_nodes(TreeNode *root) {",
			"    if (!root)",
			"        return 0;",
			"    return 1 + count_nodes(root->left) + count_nodes(root->right);",
			"}",
			"void store_in_arr(TreeNode *node, int arr[], int &index) {",
			"    if (!node)",
			"        return;",
			"    store_in_arr(node->left, arr, index);",
			"    arr[index++] = node->data;",
			"    store_in_arr(node->right, arr, index);",
			"}",
			"TreeNode *sorted_array_to_bst(int arr[], int start, int end) {",
			"    if (start > end)",
			"        return nullptr;",
			"    int mid = start + (end - start) / 2;",
			"    TreeNode *node = new TreeNode(arr[mid]);",
			"    node->left = sorted_array_to_bst(arr, start, mid - 1);",
			"    node->right = sorted_array_to_bst(arr, mid + 1, end);",
			"    return node;",
			"}",
			"void inorderTraversal(TreeNode *node) {",
			"    if (node != nullptr) {",
			"        inorderTraversal(node->left);",
			"        cout << node->data << \" \";",
			"        inorderTraversal(node->right);",
			"    }",
			"}",
			"void create_bst_from_bt(TreeNode *&root) {",
			"    int n = count_nodes(root);",
			"    int *arr = new int[n];",
			"    int index = 0;",
			"    store_in_arr(root, arr, index);",
			"    sort(arr, arr + n);",
			"    root = sorted_array_to_bst(arr, 0, n - 1);",
			"}",
			"int main() {",
			"    TreeNode *root = new TreeNode(10);",
			"    root->left = new TreeNode(15);",
			"    root->right = new TreeNode(3);",
			"    root->left->left = new TreeNode(5);",
			"    root->left->right = new TreeNode(21);",
			"    root->right->left = new TreeNode(18);",
			"    root->right->right = new TreeNode(7);",
			"    inorderTraversal(root);",
			"    cout << endl;",
			"    create_bst_from_bt(root);",
			"    inorderTraversal(root);",
			"}"
		],
		"description": "C++ Program to Convert Binary Tree to Balanced Binary Search Tree"
	},
	"Infix to Postfix": {
		"prefix": "Infix_to_Postfix",
		"body": [
			"#include <iostream>",
			"#include <string>",
			"#include <cctype>",
			"#include <cmath>",
			"#include <iomanip>",
			"using namespace std;",
			"\nclass Node",
			"{",
			"public:",
			"\tstring data;",
			"\tNode *next;",
			"\n\tNode(string value)",
			"\t{",
			"\t\tdata = value;",
			"\t\tnext = nullptr;",
			"\t}",
			"};",
			"\nclass Stack",
			"{",
			"private:",
			"\tNode *top;",
			"\npublic:",
			"\tStack() : top(nullptr) {}",
			"\n\t~Stack()",
			"\t{",
			"\t\twhile (top)",
			"\t\t{",
			"\t\t\tNode *temp = top;",
			"\t\t\ttop = top->next;",
			"\t\t\tdelete temp;",
			"\t\t}",
			"\t}",
			"\n\tvoid push(string value)",
			"\t{",
			"\t\tNode *newNode = new Node(value);",
			"\t\tnewNode->next = top;",
			"\t\ttop = newNode;",
			"\t}",
			"\n\tstring pop()",
			"\t{",
			"\t\tif (top == nullptr)",
			"\t\t{",
			"\t\t\treturn \"\";",
			"\t\t}",
			"\n\t\tstring value = top->data;",
			"\t\tNode *temp = top;",
			"\t\ttop = top->next;",
			"\t\tdelete temp;",
			"\t\treturn value;",
			"\t}",
			"\n\tstring peek()",
			"\t{",
			"\t\tif (top)",
			"\t\t\treturn top->data;",
			"\n\t\treturn \"\";",
			"\t}",
			"\n\tbool isEmpty()",
			"\t{",
			"\t\treturn (top == nullptr);",
			"\t}",
			"};",
			"\nint precedence(char op)",
			"{",
			"\tif (op == '+' || op == '-')",
			"\t\treturn 1;",
			"\telse if (op == '*' || op == '/')",
			"\t\treturn 2;",
			"\telse if (op == '^')",
			"\t\treturn 3;",
			"\n\treturn -1;",
			"}",
			"\nbool isOperator(char op)",
			"{",
			"\tif (op == '+' || op == '-' || op == '*' || op == '/' || op == '^')",
			"\t\treturn true;",
			"\n\treturn false;",
			"}",
			"\nstring infixToPostfix(const string &infix)",
			"{",
			"\tStack st;",
			"\tstring postfix;",
			"\tstring number;",
			"\n\tfor (int i = 0; i < infix.length(); ++i)",
			"\t{",
			"\t\tchar c = infix[i];",
			"\t\tif (isdigit(c) || c == '.')",
			"\t\t{",
			"\t\t\tnumber += c;",
			"\t\t}",
			"\t\telse",
			"\t\t{",
			"\t\t\tif (!number.empty())",
			"\t\t\t{",
			"\t\t\t\tpostfix += number + ' ';",
			"\t\t\t\tnumber.clear();",
			"\t\t\t}",
			"\t\t\tif (isalpha(c))",
			"\t\t\t{",
			"\t\t\t\tpostfix += c;",
			"\t\t\t}",
			"\t\t\telse if (c == '(')",
			"\t\t\t{",
			"\t\t\t\tst.push(string(1, c));",
			"\t\t\t}",
			"\t\t\telse if (c == ')')",
			"\t\t\t{",
			"\t\t\t\twhile (!st.isEmpty() && st.peek()[0] != '(')",
			"\t\t\t\t{",
			"\t\t\t\t\tpostfix += st.pop() + ' ';",
			"\t\t\t\t}",
			"\t\t\t\tst.pop();",
			"\t\t\t}",
			"\t\t\telse if (isOperator(c))",
			"\t\t\t{",
			"\t\t\t\twhile (!st.isEmpty() && precedence(st.peek()[0]) >= precedence(c))",
			"\t\t\t\t{",
			"\t\t\t\t\tpostfix += st.pop() + ' ';",
			"\t\t\t\t}",
			"\t\t\t\tst.push(string(1, c));",
			"\t\t\t}",
			"\t\t}",
			"\t}",
			"\n\tif (!number.empty())",
			"\t{",
			"\t\tpostfix += number + ' ';",
			"\t}",
			"\n\twhile (!st.isEmpty())",
			"\t{",
			"\t\tpostfix += st.pop() + ' ';",
			"\t}",
			"\n\treturn postfix;",
			"}",
			"\ndouble evaluatePostfix(const string &postfix)",
			"{",
			"\tStack st;",
			"\tstring token;",
			"\tfor (int i = 0; i < postfix.length(); ++i)",
			"\t{",
			"\t\tchar c = postfix[i];",
			"\t\tif (isdigit(c) || c == '.')",
			"\t\t{",
			"\t\t\ttoken += c;",
			"\t\t}",
			"\t\telse if (c == ' ' && !token.empty())",
			"\t\t{",
			"\t\t\tst.push(token);",
			"\t\t\ttoken.clear();",
			"\t\t}",
			"\t\telse if (isOperator(c))",
			"\t\t{",
			"\t\t\tdouble op2 = stod(st.pop());",
			"\t\t\tdouble op1 = stod(st.pop());",
			"\n\t\t\tdouble result;",
			"\n\t\t\tif (c == '+')",
			"\t\t\t\tresult = op1 + op2;",
			"\t\t\telse if (c == '-')",
			"\t\t\t\tresult = op1 - op2;",
			"\t\t\telse if (c == '*')",
			"\t\t\t\tresult = op1 * op2;",
			"\t\t\telse if (c == '/')",
			"\t\t\t\tresult = op1 / op2;",
			"\t\t\telse if (c == '^')",
			"\t\t\t\tresult = pow(op1, op2);",
			"\t\t\telse",
			"\t\t\t\treturn 0;",
			"\n\t\t\tst.push(to_string(result));",
			"\t\t}",
			"\t}",
			"\n\treturn stod(st.pop());",
			"}",
			"\nint main()",
			"{",
			"\tstring expression = \"12+13-5*(0.5+0.5)+1\";",
			"\tstring infix = \"x=\" + expression;",
			"\n\tcout << \"Infix Expression: \" << infix << endl << endl;",
			"\n\tstring postfix = infixToPostfix(expression);",
			"\tcout << \"Postfix Expression: \" << postfix << endl;",
			"\n\tdouble result = evaluatePostfix(postfix);",
			"\n\tcout << fixed << setprecision(2);",
			"\tcout << \"Result: \" << result << endl;",
			"\n\tStack st;",
			"\tst.push(\"x=\");",
			"\tst.push(to_string(result));",
			"\n\tcout << \"\\nFinal Stack Contents:\" << endl;",
			"\n\tstring value = st.pop();",
			"\tcout << fixed << setprecision(2) << stod(value) << endl;",
			"\tstring x = st.pop();",
			"\tcout << x << endl;",
			"\n\tcout << x << fixed << setprecision(2) << stod(value) << endl;",
			"\n\treturn 0;",
			"}"
		],
		"description": "C++ code for infix to postfix conversion and evaluation using a custom stack implementation"
	},
	"AVL Tree Implementation": {
		"prefix": "avltree",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"class Node {",
			"public:",
			"    Node *left;",
			"    Node *right;",
			"    int key;",
			"    int height;",
			"    Node(int k) {",
			"        left = nullptr;",
			"        right = nullptr;",
			"        key = k;",
			"        height = 0;",
			"    }",
			"};",
			"class BST {",
			"public:",
			"    Node *root;",
			"    BST() { root = nullptr; }",
			"    Node *rotateLeft(Node *x) {",
			"        Node *y = x->right;",
			"        x->right = y->left;",
			"        y->left = x;",
			"        return y;",
			"    }",
			"    Node *rotateRight(Node *x) {",
			"        Node *y = x->left;",
			"        x->left = y->right;",
			"        y->right = x;",
			"        return y;",
			"    }",
			"    Node *balance(Node *root, int ky) {",
			"        root->height = getheight(root);",
			"        int bf = getbalance(root);",
			"        if (bf > 1 && ky < root->left->key) {",
			"            return rotateRight(root);",
			"        }",
			"        if (bf < -1 && ky > root->right->key) {",
			"            return rotateLeft(root);",
			"        }",
			"        if (bf < -1 && ky < root->right->key) {",
			"            root->right = rotateRight(root->right);",
			"            return rotateLeft(root);",
			"        }",
			"        if (bf > 1 && ky > root->left->key) {",
			"            root->left = rotateLeft(root->left);",
			"            return rotateRight(root);",
			"        }",
			"        return root;",
			"    }",
			"    void insert(Node *&root, int ky) {",
			"        if (!root) {",
			"            root = new Node(ky);",
			"            return;",
			"        }",
			"        if (ky < root->key) {",
			"            insert(root->left, ky);",
			"        } else {",
			"            insert(root->right, ky);",
			"        }",
			"        root = balance(root, ky);",
			"    }",
			"    int getheight(Node *root) {",
			"        if (root == nullptr) {",
			"            return 0;",
			"        } else {",
			"            return 1 + max(getheight(root->left), getheight(root->right));",
			"        }",
			"    }",
			"    int getbalance(Node *root) {",
			"        return getheight(root->left) - getheight(root->right);",
			"    }",
			"    void inorder(Node *root) {",
			"        if (root == nullptr) return;",
			"        inorder(root->left);",
			"        cout << root->key << \" \";",
			"        inorder(root->right);",
			"    }",
			"    void deleteNode(Node *&root, int k) {",
			"        if (root == nullptr) return;",
			"        if (k < root->key) {",
			"            deleteNode(root->left, k);",
			"        } else if (k > root->key) {",
			"            deleteNode(root->right, k);",
			"        } else {",
			"            if (root->left == nullptr || root->right == nullptr) {",
			"                Node *temp = root->left ? root->left : root->right;",
			"                delete root;",
			"                root = temp;",
			"                return;",
			"            }",
			"            Node *temp = minValueNode(root->right);",
			"            root->key = temp->key;",
			"            deleteNode(root->right, temp->key);",
			"        }",
			"        root = balance(root, k);",
			"    }",
			"    Node *minValueNode(Node *root) {",
			"        Node *current = root;",
			"        while (current && current->left != nullptr) {",
			"            current = current->left;",
			"        }",
			"        return current;",
			"    }",
			"};",
			"int main() {",
			"    BST b;",
			"    b.insert(b.root, 12);",
			"    b.insert(b.root, 62);",
			"    b.insert(b.root, 2);",
			"    b.insert(b.root, 1);",
			"    b.insert(b.root, 132);",
			"    b.insert(b.root, 72);",
			"    b.insert(b.root, 162);",
			"    b.inorder(b.root);",
			"    cout << endl;",
			"    return 0;",
			"}"
		],
		"description": "C++ AVL Tree Implementation"
	},
	"BST Implementation": {
		"prefix": "bst",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"class Node {",
			"public:",
			"    Node *left;",
			"    Node *right;",
			"    int key;",
			"    Node(int k) {",
			"        left = nullptr;",
			"        right = nullptr;",
			"        key = k;",
			"    }",
			"};",
			"class BST {",
			"public:",
			"    Node *root;",
			"    BST() {",
			"        root = nullptr;",
			"    }",
			"    void insert(Node *&root, int ky) {",
			"        if (!root) {",
			"            root = new Node(ky);",
			"        } else {",
			"            if (ky < root->key) {",
			"                insert(root->left, ky);",
			"            } else {",
			"                insert(root->right, ky);",
			"            }",
			"        }",
			"    }",
			"    void inorder(Node *root) {",
			"        if (root == nullptr)",
			"            return;",
			"        inorder(root->left);",
			"        cout << root->key << \" \";",
			"        inorder(root->right);",
			"    }",
			"    void deleteNode(Node *&root, int k) {",
			"        if (root == nullptr) {",
			"            return;",
			"        }",
			"        if (k < root->key) {",
			"            deleteNode(root->left, k);",
			"        } else if (k > root->key) {",
			"            deleteNode(root->right, k);",
			"        } else {",
			"            if (root->left == nullptr) {",
			"                Node *temp = root->right;",
			"                delete root;",
			"                root = temp;",
			"            } else if (root->right == nullptr) {",
			"                Node *temp = root->left;",
			"                delete root;",
			"                root = temp;",
			"            } else {",
			"                Node *temp = minValueNode(root->right);",
			"                root->key = temp->key;",
			"                deleteNode(root->right, temp->key);",
			"            }",
			"        }",
			"    }",
			"    Node *minValueNode(Node *node) {",
			"        Node *current = node;",
			"        while (current && current->left != nullptr) {",
			"            current = current->left;",
			"        }",
			"        return current;",
			"    }",
			"};",
			"int main() {",
			"    BST b;",
			"    b.insert(b.root, 12);",
			"    b.insert(b.root, 62);",
			"    b.insert(b.root, 2);",
			"    b.insert(b.root, 1);",
			"    b.insert(b.root, 132);",
			"    b.insert(b.root, 72);",
			"    b.insert(b.root, 162);",
			"    b.inorder(b.root);",
			"    cout << endl;",
			"    b.deleteNode(b.root, 72);",
			"    b.inorder(b.root);",
			"    return 0;",
			"}"
		],
		"description": "C++ Binary Search Tree (BST) Implementation"
	},
	"hashing": {
		"prefix": "LinearProbing",
		"body": [
			"#include <iostream>",
			"#include <cmath>",
			"using namespace std;",
			"",
			"class HashTable",
			"{",
			"private:",
			"    int *table;                // Array to store hash table",
			"    int capacity;              // Maximum capacity of the hash table",
			"    int size;                  // Current number of elements in the table",
			"    float loadFactorThreshold; // Load factor threshold for rehashing",
			"",
			"    // Primary hash function: Computes hash index for a given key (using modulo)",
			"    int hash(int key)",
			"    {",
			"        return key % capacity;",
			"    }",
			"",
			"    // Mid-Square Hashing: Hash value based on squaring the key and extracting middle digits",
			"    int midSquareHash(int key)",
			"    {",
			"        int squared = key * key;",
			"        int mid = (squared / 100) % 100; // Extract middle two digits",
			"        return mid % capacity;",
			"    }",
			"",
			"    // Folding Hashing: Divides the key into chunks, sums them, and applies modulo",
			"    int foldingHash(int key)",
			"    {",
			"        int sum = 0;",
			"        while (key > 0)",
			"        {",
			"            sum += key % 100; // Take two digits at a time",
			"            key /= 100;",
			"        }",
			"        return sum % capacity;",
			"    }",
			"",
			"    // Rehash function: Resizes the table and reinserts all existing elements",
			"    void rehash()",
			"    {",
			"        int oldCapacity = capacity;",
			"        int *oldTable = table;",
			"",
			"        capacity *= 2;             // Double the capacity",
			"        table = new int[capacity]; // Create a new table",
			"        for (int i = 0; i < capacity; i++)",
			"        {",
			"            table[i] = -1; // Initialize all entries as empty",
			"        }",
			"        size = 0; // Reset size",
			"",
			"        // Reinsert all existing elements into the new table",
			"        for (int i = 0; i < oldCapacity; i++)",
			"        {",
			"            if (oldTable[i] != -1)",
			"            {",
			"                insert(oldTable[i]); // Reinsert valid elements",
			"            }",
			"        }",
			"",
			"        delete[] oldTable; // Free the memory of the old table",
			"    }",
			"",
			"    // Calculates the current load factor",
			"    float getLoadFactor()",
			"    {",
			"        return (float)size / capacity;",
			"    }",
			"",
			"public:",
			"    // Constructor: Initializes the hash table with default values",
			"    HashTable(int initialCapacity = 10, float threshold = 0.7)",
			"    {",
			"        capacity = initialCapacity;",
			"        table = new int[capacity];",
			"        for (int i = 0; i < capacity; i++)",
			"        {",
			"            table[i] = -1; // -1 indicates an empty slot",
			"        }",
			"        size = 0;",
			"        loadFactorThreshold = threshold;",
			"    }",
			"",
			"    // Insert function: Adds a key to the hash table using linear probing",
			"    void insert(int key)",
			"    {",
			"        if (getLoadFactor() > loadFactorThreshold)",
			"        {",
			"            cout << \"Load factor exceeded. Rehashing...\" << endl;",
			"            rehash();",
			"        }",
			"",
			"        int index = hash(key); // Compute the initial hash index",
			"        while (table[index] != -1)",
			"        {",
			"            index = (index + 1) % capacity; // Linear probing to find the next empty slot",
			"        }",
			"        table[index] = key; // Insert the key at the found index",
			"        size++;             // Increment the size of the table",
			"    }",
			"",
			"    // Search function: Finds a key in the hash table and returns its index",
			"    int search(int key)",
			"    {",
			"        int index = hash(key);",
			"        int startIndex = index; // Save the starting index for circular probing",
			"",
			"        while (table[index] != -1)",
			"        {",
			"            if (table[index] == key)",
			"            {",
			"                return index; // Key found",
			"            }",
			"            index = (index + 1) % capacity; // Linear probing",
			"            if (index == startIndex)",
			"            {",
			"                break; // Stop searching when we've looped back to the start",
			"            }",
			"        }",
			"        return -1; // Key not found",
			"    }",
			"",
			"    // Display function: Prints the current state of the hash table",
			"    void display()",
			"    {",
			"        for (int i = 0; i < capacity; i++)",
			"        {",
			"            if (table[i] != -1)",
			"            {",
			"                cout << i << \": \" << table[i] << endl;",
			"            }",
			"            else",
			"            {",
			"                cout << i << \": Empty\" << endl;",
			"            }",
			"        }",
			"    }",
			"",
			"    // Destructor: Frees the allocated memory for the table",
			"    ~HashTable()",
			"    {",
			"        delete[] table;",
			"    }",
			"};",
			"",
			"// Main function to demonstrate the hash table functionality",
			"int main()",
			"{",
			"    HashTable hashTable; // Create a hash table with default size and load factor",
			"",
			"    // Insert keys into the hash table",
			"    hashTable.insert(10);",
			"    hashTable.insert(20);",
			"    hashTable.insert(30);",
			"    hashTable.insert(25);",
			"    hashTable.insert(35);",
			"    hashTable.insert(15);",
			"",
			"    cout << \"Hash Table after Insertions:\" << endl;",
			"    hashTable.display();",
			"",
			"    // Search for a key in the hash table",
			"    int key = 25;",
			"    int index = hashTable.search(key);",
			"    if (index != -1)",
			"    {",
			"        cout << \"Key \" << key << \" found at index \" << index << endl;",
			"    }",
			"    else",
			"    {",
			"        cout << \"Key \" << key << \" not found.\" << endl;",
			"    }",
			"",
			"    // Demonstrate rehashing by exceeding the load factor threshold",
			"    cout << \"Inserting more elements to trigger rehashing...\" << endl;",
			"    hashTable.insert(40);",
			"    hashTable.insert(50);",
			"",
			"    cout << \"Hash Table after Rehashing:\" << endl;",
			"    hashTable.display();",
			"",
			"    return 0;",
			"}"
		],
		"description": "C++ Hash Table Implementation with Linear Probing, Rehashing, and Multiple Hashing Techniques"
	},
	"minheap": {
		"prefix": "minheap",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"class MinHeap",
			"{",
			"    int *heap;",
			"    int capacity;",
			"    int size; // current size of the min heap.",
			"    void heapify_up(int index)",
			"    {",
			"        while (index > 0)",
			"        {",
			"            int parent = (index - 1) / 2;",
			"            if (heap[index] < heap[parent])",
			"            {",
			"                swap(heap[index], heap[parent]);",
			"                index = parent;",
			"            }",
			"            else",
			"                return;",
			"        }",
			"    }",
			"    void heapify_down(int index)",
			"    {",
			"        int smallest = index;",
			"        int left = 2 * index + 1;",
			"        int right = 2 * index + 2;",
			"        if (left < size && heap[left] < heap[smallest])",
			"            smallest = left;",
			"        if (right < size && heap[right] < heap[smallest])",
			"            smallest = right;",
			"        if (smallest != index)",
			"        {",
			"            swap(heap[smallest], heap[index]);",
			"            heapify_down(smallest);",
			"        }",
			"    }",
			"public:",
			"    MinHeap(int cap = 10) : capacity(cap), size(0)",
			"    {",
			"        heap = new int[capacity];",
			"    }",
			"    ~MinHeap()",
			"    {",
			"        delete[] heap;",
			"    }",
			"    void insert(int value)",
			"    {",
			"        if (size == capacity)",
			"        {",
			"            capacity *= 2;",
			"            int *new_heap = new int[capacity];",
			"            for (int i = 0; i < size; i++)",
			"            {",
			"                new_heap[i] = heap[i];",
			"            }",
			"            delete[] heap;",
			"            heap = new_heap;",
			"        }",
			"        heap[size] = value;",
			"        heapify_up(size);",
			"        size++;",
			"    }",
			"    void remove_min()",
			"    {",
			"        if (size == 0)",
			"        {",
			"            cout << \"Heap is empty.\\n\";",
			"            return;",
			"        }",
			"        swap(heap[0], heap[size - 1]);",
			"        size--;",
			"        heapify_down(0);",
			"        for (int i = 0; i < size; i++)",
			"        {",
			"            cout << heap[i] << \" \";",
			"        }",
			"        cout << endl;",
			"    }",
			"    void remove(int value)",
			"    {",
			"        if (size == 0)",
			"        {",
			"            cout << \"Heap is empty.\\n\";",
			"            return;",
			"        }",
			"        int index = -1;",
			"        for (int i = 0; i < size; i++)",
			"        {",
			"            if (heap[i] == value)",
			"            {",
			"                index = i;",
			"                break;",
			"            }",
			"        }",
			"        if (index == -1)",
			"        {",
			"            cout << \"value not found\\n\";",
			"            return;",
			"        }",
			"        swap(heap[index], heap[size - 1]);",
			"        size--;",
			"        heapify_down(index);",
			"        for (int i = 0; i < size; i++)",
			"        {",
			"            cout << heap[i] << \" \";",
			"        }",
			"        cout << endl;",
			"    }",
			"};",
			"int main()",
			"{",
			"    MinHeap min_heap;",
			"    min_heap.insert(32);",
			"    min_heap.insert(51);",
			"    min_heap.insert(54);",
			"    min_heap.insert(42);",
			"    min_heap.insert(3);",
			"    min_heap.insert(22);",
			"    min_heap.insert(1);",
			"    min_heap.remove(22);",
			"}"
		],
		"description": "C++ MinHeap Implementation with Insert, Remove, and Heapify Functions"
	},
	"rabin_karp": {
    "prefix": "rabin_karp",
    "body": [
        "#include <iostream>",
        "using namespace std;",
        "",
        "int strlen2(char s[]) {",
        "    int i = 0;",
        "    while (s[i] != '\\0') i++;",
        "    return i;",
        "}",
        "",
        "void rabinKarp(char text[], char pat[]) {",
        "    int n = strlen2(text);",
        "    int m = strlen2(pat);",
        "",
        "    int base = 256, mod = 101;",
        "    int pHash = 0, tHash = 0, h = 1;",
        "",
        "    for (int i = 0; i < m - 1; i++) h = (h * base) % mod;",
        "",
        "    for (int i = 0; i < m; i++) {",
        "        pHash = (pHash * base + pat[i]) % mod;",
        "        tHash = (tHash * base + text[i]) % mod;",
        "    }",
        "",
        "    for (int i = 0; i <= n - m; i++) {",
        "        if (pHash == tHash) {",
        "            bool match = true;",
        "            for (int j = 0; j < m; j++)",
        "                if (text[i + j] != pat[j]) match = false;",
        "            if (match) cout << \"Pattern found at index \" << i << endl;",
        "        }",
        "",
        "        if (i < n - m) {",
        "            tHash = (tHash - text[i] * h) % mod;",
        "            tHash = (tHash * base + text[i + m]) % mod;",
        "            if (tHash < 0) tHash += mod;",
        "        }",
        "    }",
        "}",
        "",
        "int main() {",
        "    char text[] = \"abcdabcx\";",
        "    char pat[] = \"abc\";",
        "    rabinKarp(text, pat);",
        "}"
    ],
    "description": "Rabin-Karp String Search (No STL)"
},

	"kmp_search": {
    "prefix": "kmp_search",
    "body": [
        "#include <iostream>",
        "using namespace std;",
        "",
        "int strlen2(char s[]) {",
        "    int i = 0;",
        "    while (s[i] != '\\0') i++;",
        "    return i;",
        "}",
        "",
        "void buildLPS(char pat[], int m, int lps[]) {",
        "    int len = 0, i = 1;",
        "    lps[0] = 0;",
        "",
        "    while (i < m) {",
        "        if (pat[i] == pat[len]) {",
        "            lps[i++] = ++len;",
        "        } else {",
        "            if (len != 0) len = lps[len - 1];",
        "            else lps[i++] = 0;",
        "        }",
        "    }",
        "}",
        "",
        "void KMP(char text[], char pat[]) {",
        "    int n = strlen2(text);",
        "    int m = strlen2(pat);",
        "    int lps[1000];",
        "",
        "    buildLPS(pat, m, lps);",
        "",
        "    int i = 0, j = 0;",
        "",
        "    while (i < n) {",
        "        if (text[i] == pat[j]) { i++; j++; }",
        "",
        "        if (j == m) {",
        "            cout << \"Pattern found at index \" << i - j << endl;",
        "            j = lps[j - 1];",
        "        } else if (i < n && text[i] != pat[j]) {",
        "            if (j != 0) j = lps[j - 1];",
        "            else i++;",
        "        }",
        "    }",
        "}",
        "",
        "int main() {",
        "    char text[] = \"ababcababa\";",
        "    char pat[] = \"ababa\";",
        "    KMP(text, pat);",
        "}"
    ],
    "description": "KMP String Search (No STL)"
},

	"boyer_moore": {
    "prefix": "boyer_moore",
    "body": [
        "#include <iostream>",
        "using namespace std;",
        "",
        "int strlen2(char s[]) {",
        "    int i = 0;",
        "    while (s[i] != '\\0') i++;",
        "    return i;",
        "}",
        "",
        "void buildBadChar(int bad[], char pat[], int m) {",
        "    for (int i = 0; i < 256; i++) bad[i] = -1;",
        "    for (int i = 0; i < m; i++) bad[(unsigned char)pat[i]] = i;",
        "}",
        "",
        "void boyerMoore(char text[], char pat[]) {",
        "    int n = strlen2(text);",
        "    int m = strlen2(pat);",
        "    int bad[256];",
        "    buildBadChar(bad, pat, m);",
        "",
        "    int shift = 0;",
        "",
        "    while (shift <= n - m) {",
        "        int j = m - 1;",
        "",
        "        while (j >= 0 && pat[j] == text[shift + j]) j--;",
        "",
        "        if (j < 0) {",
        "            cout << \"Pattern found at index \" << shift << endl;",
        "            shift += (shift + m < n) ? m - bad[(unsigned char)text[shift + m]] : 1;",
        "        } else {",
        "            int skip = j - bad[(unsigned char)text[shift + j]];",
        "            shift += (skip > 1 ? skip : 1);",
        "        }",
        "    }",
        "}",
        "",
        "int main() {",
        "    char text[] = \"HERE IS A SIMPLE EXAMPLE\";",
        "    char pat[] = \"EXAMPLE\";",
        "    boyerMoore(text, pat);",
        "}"
    ],
    "description": "Boyer-Moore Bad Character Search (No STL)"
},

	"maxheap": {
		"prefix": "maxheap",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"",
			"class MaxHeap {",
			"    int* heap;",
			"    int capacity;",
			"    int size; // current size of the max heap",
			"",
			"    void heapify_up(int index) {",
			"        while (index > 0) {",
			"            int parent = (index - 1) / 2;",
			"            if (heap[index] > heap[parent]) {",
			"                swap(heap[index], heap[parent]);",
			"                index = parent;",
			"            } else {",
			"                return;",
			"            }",
			"        }",
			"    }",
			"",
			"    void heapify_down(int index) {",
			"        int largest = index;",
			"        int left = 2 * index + 1;",
			"        int right = 2 * index + 2;",
			"",
			"        if (left < size && heap[left] > heap[largest])",
			"            largest = left;",
			"        if (right < size && heap[right] > heap[largest])",
			"            largest = right;",
			"",
			"        if (largest != index) {",
			"            swap(heap[index], heap[largest]);",
			"            heapify_down(largest);",
			"        }",
			"    }",
			"",
			"public:",
			"    MaxHeap(int cap = 10) : capacity(cap), size(0) {",
			"        heap = new int[capacity];",
			"    }",
			"",
			"    ~MaxHeap() {",
			"        delete[] heap;",
			"    }",
			"",
			"    void insert(int value) {",
			"        if (size == capacity) {",
			"            capacity *= 2;",
			"            int* new_heap = new int[capacity];",
			"            for (int i = 0; i < size; i++) {",
			"                new_heap[i] = heap[i];",
			"            }",
			"            delete[] heap;",
			"            heap = new_heap;",
			"        }",
			"        heap[size] = value;",
			"        heapify_up(size);",
			"        size++;",
			"    }",
			"",
			"    void remove_max() {",
			"        if (size == 0) {",
			"            cout << \"Heap is empty.\\n\";",
			"            return;",
			"        }",
			"        swap(heap[0], heap[size - 1]);",
			"        size--;",
			"        heapify_down(0);",
			"        for (int i = 0; i < size; i++) {",
			"            cout << heap[i] << \" \";",
			"        }",
			"        cout << endl;",
			"    }",
			"",
			"    void remove(int value) {",
			"        if (size == 0) {",
			"            cout << \"Heap is empty.\\n\";",
			"            return;",
			"        }",
			"        int index = -1;",
			"        for (int i = 0; i < size; i++) {",
			"            if (heap[i] == value) {",
			"                index = i;",
			"                break;",
			"            }",
			"        }",
			"        if (index == -1) {",
			"            cout << \"Value not found\\n\";",
			"            return;",
			"        }",
			"        swap(heap[index], heap[size - 1]);",
			"        size--;",
			"        heapify_down(index);",
			"        for (int i = 0; i < size; i++) {",
			"            cout << heap[i] << \" \";",
			"        }",
			"        cout << endl;",
			"    }",
			"};",
			"",
			"int main() {",
			"    MaxHeap max_heap;",
			"    max_heap.insert(5);",
			"    max_heap.insert(4);",
			"    max_heap.insert(3);",
			"    max_heap.insert(2);",
			"    max_heap.insert(1);",
			"",
			"    max_heap.remove(3); // Remove 3 from the heap",
			"    max_heap.remove_max(); // Remove the maximum element",
			"}"
		],
		"description": "C++ MaxHeap Implementation with Insert, Remove, and Heapify Functions"
	},
	"minheapsort": {
		"prefix": "minheapsort",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"",
			"// Function to heapify a subtree rooted at index `i` in a Min Heap",
			"void minHeapify(int arr[], int n, int i) {",
			"    int smallest = i;",
			"    int left = 2 * i + 1;",
			"    int right = 2 * i + 2;",
			"",
			"    if (left < n && arr[left] < arr[smallest])",
			"        smallest = left;",
			"",
			"    if (right < n && arr[right] < arr[smallest])",
			"        smallest = right;",
			"",
			"    if (smallest != i) {",
			"        swap(arr[i], arr[smallest]);",
			"        minHeapify(arr, n, smallest);",
			"    }",
			"}",
			"",
			"// Function to perform heap sort in descending order using Min Heap",
			"void minHeapSort(int arr[], int n) {",
			"    // Build Min Heap",
			"    for (int i = n / 2 - 1; i >= 0; i--) {",
			"        minHeapify(arr, n, i);",
			"    }",
			"",
			"    // Extract elements from heap one by one",
			"    for (int i = n - 1; i >= 0; i--) {",
			"        swap(arr[0], arr[i]); // Move current root to end",
			"        minHeapify(arr, i, 0); // Heapify reduced heap",
			"    }",
			"}",
			"",
			"int main() {",
			"    int arr[] = {5, 4, 3, 2, 1};",
			"    int n = sizeof(arr) / sizeof(arr[0]);",
			"",
			"    minHeapSort(arr, n);",
			"",
			"    cout << \"Min Heap Sorted array: \";",
			"    for (int i = 0; i < n; i++)",
			"        cout << arr[i] << \" \";",
			"    cout << endl;",
			"    return 0;",
			"}"
		],
		"description": "C++ program to sort an array in descending order using Min Heap"
	},
	"maxheapsort": {
		"prefix": "maxheapsort",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"",
			"// Function to heapify a subtree rooted at index `i` in a Max Heap",
			"void maxHeapify(int arr[], int n, int i) {",
			"    int largest = i;",
			"    int left = 2 * i + 1;",
			"    int right = 2 * i + 2;",
			"",
			"    if (left < n && arr[left] > arr[largest])",
			"        largest = left;",
			"",
			"    if (right < n && arr[right] > arr[largest])",
			"        largest = right;",
			"",
			"    if (largest != i) {",
			"        swap(arr[i], arr[largest]);",
			"        maxHeapify(arr, n, largest);",
			"    }",
			"}",
			"",
			"// Function to perform heap sort in ascending order using Max Heap",
			"void maxHeapSort(int arr[], int n) {",
			"    // Build Max Heap",
			"    for (int i = n / 2 - 1; i >= 0; i--) {",
			"        maxHeapify(arr, n, i);",
			"    }",
			"",
			"    // Extract elements from heap one by one",
			"    for (int i = n - 1; i >= 0; i--) {",
			"        swap(arr[0], arr[i]); // Move current root to end",
			"        maxHeapify(arr, i, 0); // Heapify reduced heap",
			"    }",
			"}",
			"",
			"int main() {",
			"    int arr[] = {5, 4, 3, 2, 1};",
			"    int n = sizeof(arr) / sizeof(arr[0]);",
			"",
			"    maxHeapSort(arr, n);",
			"",
			"    cout << \"Max Heap Sorted array: \";",
			"    for (int i = 0; i < n; i++)",
			"        cout << arr[i] << \" \";",
			"    cout << endl;",
			"    return 0;",
			"}"
		],
		"description": "C++ program to sort an array in ascending order using Max Heap"
	},
	"TwoThreeTreeSnippet": {
		"prefix": "twothreetree",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"",
			"class Node {",
			"public:",
			"    int keys[2];",
			"    Node* children[3];",
			"    int numKeys;",
			"    bool isLeaf;",
			"",
			"    Node() {",
			"        keys[0] = keys[1] = 0;",
			"        children[0] = children[1] = children[2] = nullptr;",
			"        numKeys = 0;",
			"        isLeaf = true;",
			"    }",
			"};",
			"",
			"class TwoThreeTree {",
			"private:",
			"    Node* root;",
			"",
			"    void insertHelper(Node*& node, int value);",
			"    void split(Node*& node);",
			"    void inOrderHelper(Node* node);",
			"    Node* searchHelper(Node* node, int value);",
			"    void deleteHelper(Node*& node, int value);",
			"",
			"public:",
			"    TwoThreeTree() { root = new Node(); }",
			"    void insert(int value);",
			"    void inOrderTraversal();",
			"    Node* search(int value);",
			"    void remove(int value);",
			"};",
			"",
			"void TwoThreeTree::insert(int value) {",
			"    insertHelper(root, value);",
			"}",
			"",
			"void TwoThreeTree::insertHelper(Node*& node, int value) {",
			"    if (node->isLeaf) {",
			"        if (node->numKeys == 0 || value < node->keys[0]) {",
			"            node->keys[1] = node->keys[0];",
			"            node->keys[0] = value;",
			"        } else {",
			"            node->keys[1] = value;",
			"        }",
			"        node->numKeys++;",
			"    } else {",
			"        if (value < node->keys[0])",
			"            insertHelper(node->children[0], value);",
			"        else if (node->numKeys == 1 || value < node->keys[1])",
			"            insertHelper(node->children[1], value);",
			"        else",
			"            insertHelper(node->children[2], value);",
			"    }",
			"    if (node->numKeys == 2 && node->children[0]) {",
			"        split(node);",
			"    }",
			"}",
			"",
			"void TwoThreeTree::split(Node*& node) {",
			"    int midValue = node->keys[1];",
			"    Node* newChild = new Node();",
			"    newChild->keys[0] = node->keys[1];",
			"    newChild->numKeys = 1;",
			"    newChild->isLeaf = node->isLeaf;",
			"    node->numKeys = 1;",
			"    node->children[2] = nullptr;",
			"    if (!root->children[0]) {",
			"        Node* newRoot = new Node();",
			"        newRoot->keys[0] = midValue;",
			"        newRoot->children[0] = node;",
			"        newRoot->children[1] = newChild;",
			"        newRoot->numKeys = 1;",
			"        root = newRoot;",
			"    } else {",
			"        insertHelper(root, midValue);",
			"    }",
			"}",
			"",
			"Node* TwoThreeTree::search(int value) {",
			"    return searchHelper(root, value);",
			"}",
			"",
			"Node* TwoThreeTree::searchHelper(Node* node, int value) {",
			"    if (!node) return nullptr;",
			"",
			"    for (int i = 0; i < node->numKeys; ++i) {",
			"        if (node->keys[i] == value) return node;",
			"    }",
			"",
			"    if (node->isLeaf) return nullptr;",
			"    if (value < node->keys[0]) return searchHelper(node->children[0], value);",
			"    if (node->numKeys == 1 || value < node->keys[1]) return searchHelper(node->children[1], value);",
			"    return searchHelper(node->children[2], value);",
			"}",
			"",
			"void TwoThreeTree::remove(int value) {",
			"    deleteHelper(root, value);",
			"}",
			"",
			"void TwoThreeTree::deleteHelper(Node*& node, int value) {",
			"    if (!node) return;",
			"    if (node->isLeaf) {",
			"        if (node->keys[0] == value) {",
			"            node->keys[0] = node->keys[1];",
			"            node->numKeys--;",
			"        } else if (node->keys[1] == value) {",
			"            node->numKeys--;",
			"        }",
			"        return;",
			"    }",
			"    int index = (value < node->keys[0]) ? 0 : (node->numKeys == 1 || value < node->keys[1]) ? 1 : 2;",
			"    deleteHelper(node->children[index], value);",
			"}",
			"",
			"void TwoThreeTree::inOrderTraversal() {",
			"    inOrderHelper(root);",
			"    cout << endl;",
			"}",
			"",
			"void TwoThreeTree::inOrderHelper(Node* node) {",
			"    if (!node) return;",
			"    inOrderHelper(node->children[0]);",
			"    if (node->numKeys > 0) cout << node->keys[0] << \" \";",
			"    inOrderHelper(node->children[1]);",
			"    if (node->numKeys > 1) cout << node->keys[1] << \" \";",
			"    inOrderHelper(node->children[2]);",
			"}",
			"",
			"int main() {",
			"    TwoThreeTree tree;",
			"    tree.insert(10);",
			"    tree.insert(20);",
			"    tree.insert(5);",
			"    tree.insert(15);",
			"    tree.insert(25);",
			"",
			"    cout << \"In-order traversal: \";",
			"    tree.inOrderTraversal();",
			"",
			"    Node* found = tree.search(15);",
			"    if (found) cout << \"Found: 15\\n\";",
			"    else cout << \"Not found: 15\\n\";",
			"",
			"    tree.remove(15);",
			"    cout << \"After deletion: \";",
			"    tree.inOrderTraversal();",
			"    return 0;",
			"}"
		],
		"description": "2-3 Tree with insert, delete, search, and in-order traversal."
	}
}
