{
	// Place your snippets for cpp here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
	// same ids are connected.
	// Example:
	"code": {
		"prefix": "code",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"int main() {",
			"\t",
			"\treturn 0;",
			"}"
		],
		"description": "code"
	},
	"ll": {
		"prefix": "ll",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"",
			"class Node{",
			"public:",
			"    int data;",
			"    Node* next;",
			"    Node(int v):data(v),next(NULL){}",
			"};",
			"",
			"class List{",
			"    Node* head;",
			"    Node* tail;",
			"public:",
			"    List():head(NULL),tail(NULL){}",
			"",
			"    void pushfront(int v){",
			"        Node* n=new Node(v);",
			"        if(!head) head=tail=n;",
			"        else{ n->next=head; head=n; }",
			"    }",
			"",
			"    void pushback(int v){",
			"        Node* n=new Node(v);",
			"        if(!head){ head=tail=n; return; }",
			"        tail->next=n;",
			"        tail=n;",
			"    }",
			"",
			"    void popfront(){",
			"        if(!head) return;",
			"        if(head==tail){ delete head; head=tail=NULL; return; }",
			"        Node* t=head;",
			"        head=head->next;",
			"        delete t;",
			"    }",
			"",
			"    void popback(){",
			"        if(!head) return;",
			"        if(head==tail){ delete head; head=tail=NULL; return; }",
			"        Node* t=head;",
			"        while(t->next!=tail) t=t->next;",
			"        delete tail;",
			"        tail=t;",
			"        tail->next=NULL;",
			"    }",
			"",
			"    void insert_at(int v,int pos){",
			"        if(pos<=1){ pushfront(v); return; }",
			"        Node* t=head;",
			"        for(int i=1;i<pos-1 && t;i++) t=t->next;",
			"        if(!t) return;",
			"        Node* n=new Node(v);",
			"        n->next=t->next;",
			"        t->next=n;",
			"        if(n->next==NULL) tail=n;",
			"    }",
			"",
			"    int search(int key){",
			"        Node* t=head;",
			"        int i=0;",
			"        while(t){",
			"            if(t->data==key) return i;",
			"            t=t->next;",
			"            i++;",
			"        }",
			"        return -1;",
			"    }",
			"",
			"    void display(){",
			"        Node* t=head;",
			"        while(t){ cout<<t->data<<\"->\"; t=t->next; }",
			"        cout<<\"NULL\\n\";",
			"    }",
			"};",
			"",
			"int main(){",
			"    List ll;",
			"    ll.pushfront(3);",
			"    ll.pushfront(2);",
			"    ll.pushfront(1);",
			"    ll.popfront();",
			"    ll.popfront();",
			"    ll.display();",
			"    return 0;",
			"}"
		],
		"description": "Linked List Boilerplate Snippet"
	},
		"avl": {
		"prefix": "avl",
		"body": [
			"#include<iostream>",
			"using namespace std;",
			"struct Node{",
			"    int data;",
			"    Node* left;",
			"    Node* right;",
			"    int height;",
			"    Node(int val){ data=val; left=right=NULL; height=1; }",
			"};",
			"class AVL{",
			"    Node* root;",
			"    int get_height(Node* node){ return node?node->height:0; }",
			"    int get_balance(Node* node){ return node?get_height(node->left)-get_height(node->right):0; }",
			"    void update_height(Node* node){ node->height=1+max(get_height(node->left),get_height(node->right)); }",
			"    Node* rotate_right(Node* y){",
			"        Node* x=y->left; Node* T2=x->right;",
			"        x->right=y; y->left=T2;",
			"        update_height(y); update_height(x);",
			"        return x;",
			"    }",
			"    Node* rotate_left(Node* x){",
			"        Node* y=x->right; Node* T2=y->left;",
			"        y->left=x; x->right=T2;",
			"        update_height(x); update_height(y);",
			"        return y;",
			"    }",
			"    Node* balance_node(Node* node){",
			"        int balance=get_balance(node);",
			"        if(balance>1 && get_balance(node->left)>=0) return rotate_right(node);",
			"        if(balance>1 && get_balance(node->left)<0){ node->left=rotate_left(node->left); return rotate_right(node); }",
			"        if(balance<-1 && get_balance(node->right)<=0) return rotate_left(node);",
			"        if(balance<-1 && get_balance(node->right)>0){ node->right=rotate_right(node->right); return rotate_left(node); }",
			"        return node;",
			"    }",
			"    Node* insert(Node* node,int val){",
			"        if(node==NULL) return new Node(val);",
			"        if(val<node->data) node->left=insert(node->left,val);",
			"        else if(val>node->data) node->right=insert(node->right,val);",
			"        else return node;",
			"        update_height(node);",
			"        return balance_node(node);",
			"    }",
			"    Node* find_min(Node* node){ while(node && node->left) node=node->left; return node; }",
			"    Node* delete_node(Node* node,int val){",
			"        if(!node) return node;",
			"        if(val<node->data) node->left=delete_node(node->left,val);",
			"        else if(val>node->data) node->right=delete_node(node->right,val);",
			"        else{",
			"            if(!node->left || !node->right){",
			"                Node* temp=node->left?node->left:node->right;",
			"                if(!temp){ temp=node; node=NULL; }",
			"                else *node=*temp;",
			"                delete temp;",
			"            } else{",
			"                Node* temp=find_min(node->right);",
			"                node->data=temp->data;",
			"                node->right=delete_node(node->right,temp->data);",
			"            }",
			"        }",
			"        if(!node) return node;",
			"        update_height(node);",
			"        return balance_node(node);",
			"    }",
			"    void inorder(Node* node){",
			"        if(node){ inorder(node->left); cout<<node->data<<\" \"; inorder(node->right); }",
			"    }",
			"public:",
			"    AVL(){ root=NULL; }",
			"    void insert(int val){ root=insert(root,val); }",
			"    void remove(int val){ root=delete_node(root,val); }",
			"    void display(){ inorder(root); cout<<endl; }",
			"};",
			"int main(){",
			"    AVL tree;",
			"    tree.insert(20);",
			"    tree.insert(40);",
			"    tree.insert(30);",
			"    cout<<\"Inorder before deletion: \"; tree.display();",
			"    tree.remove(40);",
			"    cout<<\"Inorder after deletion: \"; tree.display();",
			"    return 0;",
			"}"
		],
		"description": "AVL Tree with insertion, deletion, and inorder display"
	},
		"bst": {
		"prefix": "bst",
		"body": [
			"#include<iostream>",
			"using namespace std;",
			"struct Node {",
			"    int data;",
			"    Node* left;",
			"    Node* right;",
			"    Node(int val){ data=val; left=right=NULL; }",
			"};",
			"class BST{",
			"    Node* root;",
			"    Node* insert(Node* node,int val){",
			"        if(node==NULL) return new Node(val);",
			"        if(val<node->data) node->left=insert(node->left,val);",
			"        else if(val>node->data) node->right=insert(node->right,val);",
			"        return node;",
			"    }",
			"    Node* delete_node(Node* node,int val){",
			"        if(node==NULL) return node;",
			"        if(val<node->data) node->left=delete_node(node->left,val);",
			"        else if(val>node->data) node->right=delete_node(node->right,val);",
			"        else{",
			"            if(node->left==NULL && node->right==NULL){ delete node; return NULL; }",
			"            else if(node->left==NULL){ Node* temp=node->right; delete node; return temp; }",
			"            else if(node->right==NULL){ Node* temp=node->left; delete node; return temp; }",
			"            else{ Node* temp=find_min(node->right); node->data=temp->data; node->right=delete_node(node->right,temp->data); }",
			"        }",
			"        return node;",
			"    }",
			"    Node* find_min(Node* node){ while(node && node->left!=NULL) node=node->left; return node; }",
			"    void inorder(Node* node) const{",
			"        if(node!=NULL){ inorder(node->left); cout<<node->data<<\" \"; inorder(node->right); }",
			"    }",
			"    bool search(Node* node, int val) const{",
			"        if(node==NULL) return false;",
			"        if(node->data==val) return true;",
			"        else if(val<node->data) return search(node->left,val);",
			"        else return search(node->right,val);",
			"    }",
			"public:",
			"    BST(){ root=NULL; }",
			"    void insert(int val){ root=insert(root,val); }",
			"    void remove(int val){ root=delete_node(root,val); }",
			"    void display(){ inorder(root); cout<<endl; }",
			"    bool search(int val){ return search(root,val); }",
			"};",
			"int main(){",
			"    BST tree;",
			"    tree.insert(5);",
			"    tree.insert(3);",
			"    tree.insert(4);",
			"    tree.insert(2);",
			"    cout<<\"BST Elements: \"; tree.display();",
			"    tree.remove(3);",
			"    cout<<\"After Deletion: \"; tree.display();",
			"    int key=4;",
			"    if(tree.search(key)) cout<<key<<\" found in BST\\n\";",
			"    else cout<<key<<\" not found in BST\\n\";",
			"    key=10;",
			"    if(tree.search(key)) cout<<key<<\" found in BST\\n\";",
			"    else cout<<key<<\" not found in BST\\n\";",
			"    return 0;",
			"}"
		],
		"description": "Binary Search Tree with insert, delete, inorder display and search"
	},
	    "pre": {
        "prefix": "pre",
        "body": [
            "#include <bits/stdc++.h>",
            "using namespace std;",
            "",
            "class Stack{",
            "public:",
            "    char arr[1000];",
            "    int top;",
            "    Stack(){ top=-1; }",
            "    void push(char x){ arr[++top]=x; }",
            "    char pop(){ return arr[top--]; }",
            "    char peek(){ return arr[top]; }",
            "    bool empty(){ return top==-1; }",
            "};",
            "",
            "int prec(char c){",
            "    if(c=='^') return 3;",
            "    if(c=='*' || c=='/') return 2;",
            "    if(c=='+' || c=='-') return 1;",
            "    return 0;",
            "}",
            "",
            "string infixToPrefix(string s){",
            "    int n=s.length();",
            "    for(int i=0,j=n-1;i<j;i++,j--){ char t=s[i]; s[i]=s[j]; s[j]=t; }",
            "    for(int i=0;i<n;i++){ if(s[i]=='(') s[i]=')'; else if(s[i]==')') s[i]='('; }",
            "    Stack st;",
            "    char res[1000];",
            "    int k=0;",
            "    for(int i=0;i<n;i++){",
            "        char c=s[i];",
            "        if((c>='A'&&c<='Z')||(c>='a'&&c<='z')||(c>='0'&&c<='9')) res[k++]=c;",
            "        else if(c=='(') st.push(c);",
            "        else if(c==')'){ while(!st.empty()&&st.peek()!='(') res[k++]=st.pop(); st.pop(); }",
            "        else{ while(!st.empty()&&prec(c)<=prec(st.peek())) res[k++]=st.pop(); st.push(c); }",
            "    }",
            "    while(!st.empty()) res[k++]=st.pop();",
            "    for(int i=0,j=k-1;i<j;i++,j--){ char t=res[i]; res[i]=res[j]; res[j]=t; }",
            "    res[k]='\\0';",
            "    return string(res);",
            "}",
            "",
            "int main(){",
            "    string s;",
            "    cin>>s;",
            "    cout<<infixToPrefix(s);",
            "    return 0;",
            "}"
        ],
        "description": "Infix to Prefix (Manual Stack, No Builtins, No Comments)"
    },
		"infpo": {
		"prefix": "infpo",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"#define cap 100",
			"class Stack{",
			"    int top;",
			"    char arr[cap];",
			"    public:",
			"    Stack(){ top=-1; }",
			"    void push(char c){ if(top<cap-1) arr[++top]=c; }",
			"    void pop(){ if(top!=-1) top--; }",
			"    char peek(){ return top==-1?'?':arr[top]; }",
			"    bool isEmpty(){ return top==-1; }",
			"};",
			"int prec(char c){",
			"    if(c=='^') return 3;",
			"    if(c=='*'||c=='/') return 2;",
			"    if(c=='+'||c=='-') return 1;",
			"    return 0;",
			"}",
			"string infixToPostfix(string s){",
			"    Stack st;",
			"    string res=\"\";",
			"    for(int i=0;i<s.length();i++){",
			"        char c=s[i];",
			"        if((c>='a'&&c<='z')||(c>='A'&&c<='Z')||isdigit(c)) res+=c;",
			"        else if(c=='(') st.push(c);",
			"        else if(c==')'){",
			"            while(!st.isEmpty()&&st.peek()!='('){ res+=st.peek(); st.pop(); }",
			"            st.pop();",
			"        }",
			"        else{",
			"            while(!st.isEmpty()&&prec(st.peek())>=prec(c)){ res+=st.peek(); st.pop(); }",
			"            st.push(c);",
			"        }",
			"    }",
			"    while(!st.isEmpty()){ res+=st.peek(); st.pop(); }",
			"    return res;",
			"}",
			"int main(){",
			"    string s=\"a+(b*c)\";",
			"    cout<<infixToPostfix(s);",
			"}"
		],
		"description": "Infix to Postfix using manual stack"
	},
		"infpoev": {
		"prefix": "infpoev",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"class Node{",
			"public:",
			"    int data;",
			"    Node* next;",
			"    Node(int v){ data=v; next=NULL; }",
			"};",
			"class Stack{",
			"public:",
			"    Node* top;",
			"    Stack(){ top=NULL; }",
			"    void push(int v){ Node* n=new Node(v); n->next=top; top=n; }",
			"    int pop(){ int v=top->data; Node* t=top; top=top->next; delete t; return v; }",
			"    int peek(){ return top->data; }",
			"    bool empty(){ return top==NULL; }",
			"};",
			"int prec(char c){",
			"    if(c=='^') return 3;",
			"    if(c=='*'||c=='/') return 2;",
			"    if(c=='+'||c=='-') return 1;",
			"    return 0;",
			"}",
			"string infixToPostfix(string s){",
			"    Stack st;",
			"    string r=\"\";",
			"    for(int i=0;i<s.length();i++){",
			"        char c=s[i];",
			"        if(c>='0'&&c<='9') r+=c;",
			"        else if(c=='(') st.push(c);",
			"        else if(c==')'){",
			"            while(!st.empty()&&st.peek()!='('){ r+=st.peek(); st.pop(); }",
			"            st.pop();",
			"        }",
			"        else{",
			"            while(!st.empty()&&prec(st.peek())>=prec(c)){ r+=st.peek(); st.pop(); }",
			"            st.push(c);",
			"        }",
			"    }",
			"    while(!st.empty()){ r+=st.peek(); st.pop(); }",
			"    return r;",
			"}",
			"int evalPostfix(string p){",
			"    Stack st;",
			"    for(int i=0;i<p.length();i++){",
			"        char c=p[i];",
			"        if(c>='0'&&c<='9') st.push(c-'0');",
			"        else{",
			"            int b=st.pop();",
			"            int a=st.pop();",
			"            int r=0;",
			"            if(c=='+') r=a+b;",
			"            else if(c=='-') r=a-b;",
			"            else if(c=='*') r=a*b;",
			"            else if(c=='/') r=a/b;",
			"            else if(c=='^'){ r=1; for(int k=0;k<b;k++) r=r*a; }",
			"            st.push(r);",
			"        }",
			"    }",
			"    return st.pop();",
			"}",
			"int main(){",
			"    string s;",
			"    cin>>s;",
			"    string p=infixToPostfix(s);",
			"    cout<<p<<endl;",
			"    cout<<evalPostfix(p);",
			"}"
		],
		"description": "Infix to Postfix and Evaluate using Linked List Stack"
	},
		"ms": {
		"prefix": "ms",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"void merge(int a[], int beg, int mid, int end){",
			"    int n1 = mid - beg + 1;",
			"    int n2 = end - mid;",
			"    int LeftArray[n1], RightArray[n2];",
			"    for(int i=0;i<n1;i++) LeftArray[i]=a[beg+i];",
			"    for(int j=0;j<n2;j++) RightArray[j]=a[mid+1+j];",
			"    int i=0, j=0, k=beg;",
			"    while(i<n1 && j<n2){",
			"        if(LeftArray[i]<=RightArray[j]) a[k++]=LeftArray[i++];",
			"        else a[k++]=RightArray[j++];",
			"    }",
			"    while(i<n1) a[k++]=LeftArray[i++];",
			"    while(j<n2) a[k++]=RightArray[j++];",
			"}",
			"void mergeSort(int a[], int beg, int end){",
			"    if(beg<end){",
			"        int mid=(beg+end)/2;",
			"        mergeSort(a,beg,mid);",
			"        mergeSort(a,mid+1,end);",
			"        merge(a,beg,mid,end);",
			"    }",
			"}",
			"void printArray(int a[], int n){",
			"    for(int i=0;i<n;i++) cout<<a[i]<<\" \";",
			"    cout<<endl;",
			"}",
			"int main(){",
			"    int a[]={12,31,25,8,32,17,40,42};",
			"    int n=sizeof(a)/sizeof(a[0]);",
			"    cout<<\"Before sorting -\\n\";",
			"    printArray(a,n);",
			"    mergeSort(a,0,n-1);",
			"    cout<<\"After sorting -\\n\";",
			"    printArray(a,n);",
			"    return 0;",
			"}"
		],
		"description": "Merge Sort implementation using arrays"
	},
		"qdarr": {
		"prefix": "qdarr",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"class Queue{",
			"    int front;",
			"    int rear;",
			"    int cap;",
			"    int* arr;",
			"    public:",
			"    Queue(int c){ front=rear=-1; cap=c; arr=new int[cap]; }",
			"    void enqueue(int val){",
			"        if(rear>=cap-1){",
			"            int* newArr=new int[cap*2];",
			"            for(int i=0;i<cap;i++) newArr[i]=arr[i];",
			"            delete arr;",
			"            arr=newArr; cap*=2;",
			"        }",
			"        if(front==-1) front=0;",
			"        arr[++rear]=val;",
			"    }",
			"    void dequeue(){",
			"        if(front==-1||front>rear){ cout<<\"empty\"; return; }",
			"        front++;",
			"    }",
			"    int peek(){",
			"        if(front==-1||front>rear) return -1;",
			"        return arr[front];",
			"    }",
			"    bool isEmpty(){ return front==-1||front>rear; }",
			"};",
			"int main(){",
			"    Queue q(2);",
			"    q.enqueue(10);",
			"    q.enqueue(20);",
			"    q.enqueue(30);",
			"    while(!q.isEmpty()){ cout<<q.peek()<<\" \"; q.dequeue(); }",
			"}"
		],
		"description": "Queue using dynamic array"
	},
		"qll": {
		"prefix": "qll",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"class Node{",
			"    public:",
			"    int data;",
			"    Node* next;",
			"    Node(int val){ data=val; next=NULL; }",
			"};",
			"class Queue{",
			"    Node* front;",
			"    Node* rear;",
			"    public:",
			"    Queue(){ front=rear=NULL; }",
			"    void enqueue(int val){",
			"        Node* n=new Node(val);",
			"        if(front==NULL){ front=rear=n; return; }",
			"        rear->next=n; rear=n;",
			"    }",
			"    void dequeue(){",
			"        if(front==NULL) return;",
			"        Node* t=front;",
			"        front=front->next;",
			"        delete t;",
			"        if(front==NULL) rear=NULL;",
			"    }",
			"    int peek(){ return front?front->data:-1; }",
			"    bool isEmpty(){ return front==NULL; }",
			"};",
			"int main(){",
			"    Queue q;",
			"    q.enqueue(10);",
			"    q.enqueue(20);",
			"    q.enqueue(30);",
			"    while(!q.isEmpty()){ cout<<q.peek()<<\" \"; q.dequeue(); }",
			"}"
		],
		"description": "Queue using linked list"
	},
		"qs": {
		"prefix": "qs",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"int partition(int a[], int start, int end){",
			"    int pivot = a[end];",
			"    int i = start - 1;",
			"    for(int j=start;j<end;j++){",
			"        if(a[j]<=pivot){",
			"            i++;",
			"            int t=a[i]; a[i]=a[j]; a[j]=t;",
			"        }",
			"    }",
			"    int t=a[i+1]; a[i+1]=a[end]; a[end]=t;",
			"    return i+1;",
			"}",
			"void quick(int a[], int start, int end){",
			"    if(start<end){",
			"        int p=partition(a,start,end);",
			"        quick(a,start,p-1);",
			"        quick(a,p+1,end);",
			"    }",
			"}",
			"void printArr(int a[], int n){",
			"    for(int i=0;i<n;i++) cout<<a[i]<<\" \";",
			"    cout<<endl;",
			"}",
			"int main(){",
			"    int a[]={3,2,7,1,8};",
			"    int n=sizeof(a)/sizeof(a[0]);",
			"    cout<<\"Before sorting -\\n\";",
			"    printArr(a,n);",
			"    quick(a,0,n-1);",
			"    cout<<\"After sorting -\\n\";",
			"    printArr(a,n);",
			"    return 0;",
			"}"
		],
		"description": "Quick Sort implementation using arrays"
	},
		"qstarr": {
		"prefix": "qstarr",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"#define cap 100",
			"class Queue{",
			"    int front;",
			"    int rear;",
			"    int arr[cap];",
			"    public:",
			"    Queue(){ front=rear=-1; }",
			"    void enqueue(int val){",
			"        if(rear>=cap-1){ cout<<\"overflow\"; return; }",
			"        if(front==-1) front=0;",
			"        arr[++rear]=val;",
			"    }",
			"    void dequeue(){",
			"        if(front==-1||front>rear){ cout<<\"empty\"; return; }",
			"        front++;",
			"    }",
			"    int peek(){",
			"        if(front==-1||front>rear) return -1;",
			"        return arr[front];",
			"    }",
			"    bool isEmpty(){ return front==-1||front>rear; }",
			"};",
			"int main(){",
			"    Queue q;",
			"    q.enqueue(10);",
			"    q.enqueue(20);",
			"    q.enqueue(30);",
			"    while(!q.isEmpty()){ cout<<q.peek()<<\" \"; q.dequeue(); }",
			"}"
		],
		"description": "Queue using static array"
	},
		"rll": {
		"prefix": "rll",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"class Node{",
			"public:",
			"    int data;",
			"    Node* next;",
			"    Node(int v){ data=v; next=NULL; }",
			"};",
			"class Queue{",
			"public:",
			"    Node* front;",
			"    Node* rear;",
			"    Queue(){ front=rear=NULL; }",
			"    void enqueue(int v){",
			"        Node* n=new Node(v);",
			"        if(rear==NULL){ front=rear=n; return; }",
			"        rear->next=n; rear=n;",
			"    }",
			"    int dequeue(){",
			"        Node* t=front; int v=t->data;",
			"        front=front->next;",
			"        if(front==NULL) rear=NULL;",
			"        delete t; return v;",
			"    }",
			"    bool isEmpty(){ return front==NULL; }",
			"};",
			"int getMax(int a[], int n){",
			"    int max=a[0];",
			"    for(int i=1;i<n;i++) if(a[i]>max) max=a[i];",
			"    return max;",
			"}",
			"void radixSortLL(int a[], int n){",
			"    int max=getMax(a,n);",
			"    for(int place=1; max/place>0; place*=10){",
			"        Queue buckets[10];",
			"        for(int i=0;i<n;i++) buckets[(a[i]/place)%10].enqueue(a[i]);",
			"        int idx=0;",
			"        for(int i=0;i<10;i++){",
			"            while(!buckets[i].isEmpty()) a[idx++]=buckets[i].dequeue();",
			"        }",
			"    }",
			"}",
			"void printArray(int a[], int n){",
			"    for(int i=0;i<n;i++) cout<<a[i]<<\" \";",
			"    cout<<endl;",
			"}",
			"int main(){",
			"    int a[]={181,289,390,121,145,736,514,888,122};",
			"    int n=sizeof(a)/sizeof(a[0]);",
			"    cout<<\"Before sorting -\\n\";",
			"    printArray(a,n);",
			"    radixSortLL(a,n);",
			"    cout<<\"After Radix Sort using Linked List -\\n\";",
			"    printArray(a,n);",
			"}"
		],
		"description": "Radix Sort using Linked List buckets"
	},
		"rs": {
		"prefix": "rarr",
		"body": [
			"#include <iostream>",
			"using namespace std;",
			"int getMax(int a[], int n){",
			"    int max = a[0];",
			"    for(int i=1;i<n;i++){ if(a[i]>max) max=a[i]; }",
			"    return max;",
			"}",
			"void countingSort(int a[], int n, int place){",
			"    int output[n];",
			"    int count[10]={0};",
			"    for(int i=0;i<n;i++) count[(a[i]/place)%10]++;",
			"    for(int i=1;i<10;i++) count[i]+=count[i-1];",
			"    for(int i=n-1;i>=0;i--){",
			"        output[count[(a[i]/place)%10]-1]=a[i];",
			"        count[(a[i]/place)%10]--;",
			"    }",
			"    for(int i=0;i<n;i++) a[i]=output[i];",
			"}",
			"void radixsort(int a[], int n){",
			"    int max=getMax(a,n);",
			"    for(int place=1; max/place>0; place*=10) countingSort(a,n,place);",
			"}",
			"void printArray(int a[], int n){",
			"    for(int i=0;i<n;i++) cout<<a[i]<<\" \";",
			"    cout<<endl;",
			"}",
			"int main(){",
			"    int a[]={181,289,390,121,145,736,514,888,122};",
			"    int n=sizeof(a)/sizeof(a[0]);",
			"    cout<<\"Before sorting -\\n\";",
			"    printArray(a,n);",
			"    radixsort(a,n);",
			"    cout<<\"After Radix Sort -\\n\";",
			"    printArray(a,n);",
			"}"
		],
		"description": "Radix Sort using simple array"
	},
		"stsarr": {
		"prefix": "stsarr",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"#define cap 100",
			"class Stack{",
			"    int top;",
			"    int arr[cap];",
			"public:",
			"    Stack(){ top=-1; }",
			"    void push(int val){ if(top>=(cap-1)){} else arr[++top]=val; }",
			"    void pop(){ if(top==-1){} else top--; }",
			"    int peek(){ if(top==-1) return -1; return arr[top]; }",
			"    bool isEmpty(){ return top==-1; }",
			"};",
			"int main(){",
			"    Stack s;",
			"    s.push(10);",
			"    s.push(20);",
			"    s.push(30);",
			"    while(!s.isEmpty()){ cout<<s.peek()<<\" \"; s.pop(); }",
			"    return 0;",
			"}"
		],
		"description": "Stack using Static Array"
	},
		"stdarr": {
		"prefix": "stdarr",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"class Stack{",
			"    int top;",
			"    int* arr;",
			"    int cap;",
			"public:",
			"    Stack(int c){ top=-1; cap=c; arr=new int[cap]; }",
			"    void push(int val){",
			"        if(top>=(cap-1)){",
			"            int* newArr=new int[cap*2];",
			"            for(int i=0;i<cap;i++) newArr[i]=arr[i];",
			"            delete arr;",
			"            arr=newArr;",
			"            cap*=2;",
			"        }",
			"        arr[++top]=val;",
			"    }",
			"    void pop(){ if(top==-1){} else top--; }",
			"    int peek(){ if(top==-1) return -1; return arr[top]; }",
			"    bool isEmpty(){ return top==-1; }",
			"};",
			"int main(){",
			"    Stack s(2);",
			"    s.push(10);",
			"    s.push(20);",
			"    s.push(30);",
			"    while(!s.isEmpty()){ cout<<s.peek()<<\" \"; s.pop(); }",
			"    return 0;",
			"}"
		],
		"description": "Stack using Dynamic Array"
	},
		"stli": {
		"prefix": "stli",
		"body": [
			"#include <bits/stdc++.h>",
			"using namespace std;",
			"class Node{",
			"public:",
			"    int data;",
			"    Node* next;",
			"    Node(int val){ data=val; next=NULL; }",
			"};",
			"class Stack{",
			"    Node* top;",
			"public:",
			"    Stack(){ top=NULL; }",
			"    int count=0;",
			"    void push(int val){ Node* n=new Node(val); n->next=top; top=n; count++; }",
			"    int pop(){",
			"        if(top==NULL) return -1;",
			"        Node* t=top;",
			"        top=top->next;",
			"        int v=t->data;",
			"        delete t;",
			"        count--;",
			"        return v;",
			"    }",
			"    int peek(){ if(top==NULL) return -1; return top->data; }",
			"    bool isEmpty(){ return top==NULL; }",
			"};",
			"int main(){",
			"    Stack s;",
			"    s.push(10);",
			"    s.push(20);",
			"    s.push(30);",
			"    while(!s.isEmpty()){ cout<<s.peek()<<\" \"; s.pop(); }",
			"    return 0;",
			"}"
		],
		"description": "Stack using Linked List"
	},
}
